astropy/halotools

halotools/defaults.py
halotools/hod_factory.py
halotools/mock_factory.py

Erik forked aphearin/halotools onto astropy/halotools at a time when I had a slightly different version on my local machine. Rather than jump through rebasing hoops, I just forked from astropy/halotools onto aphearin/halotools, cloned my fork, rsync'd my changes, pushed back to aphearin/halotools, and submitted this pull request. Minor changes are only related to a slight restructuring of the mock factory.

Minor updates related to initial fork synchronization

---

docs/index.rst
halotools/utils/io_utils.py

Mostly trivial changes to index.rst

minor changes to docs to identify build failure

---

docs/index.rst

Updated astropy_helpers according to Erik's suggestion. Docs build now.

updated docs 

---

docs/getting_started.rst
docs/index.rst
docs/install.rst
docs/overview.rst

Mostly just so I have a clean copy of master. Will now begin exclusively developing with the "one task, one branch" workflow.

update to doc structure

---

README.md
docs/getting_started.rst
docs/index.rst
docs/mock_making/mock_population.rst
docs/mock_making/models.rst
docs/mock_making/overview.rst
docs/mock_making/quickstart_guide.rst
docs/mock_making/simulations.rst
docs/sim_analysis/halo_analysis.rst
docs/sim_analysis/halo_catalogs.rst
docs/sim_analysis/merger_trees.rst
docs/sim_analysis/overview.rst
docs/tutorials/convert_tutorials.py
docs/tutorials/example_tutorial.ipynb
docs/tutorials/example_tutorial.rst
halotools/defaults.py
halotools/gal_prof_components.py
halotools/hod_components.py
halotools/hod_designer.py
halotools/hod_factory.py
halotools/mock_factory.py
halotools/occupation_helpers.py

Mostly just put some infrastructure in place for composing narrative docs, as opposed to the API dump that was there before. Also included support for integrating IPython Notebooks into the docs, including a way to test that they raise no exceptions before converting them to rst files.

Reorganized documentation

---

docs/tutorials/model_building_tutorial.ipynb
docs/tutorials/model_building_tutorial.rst
halotools/empirical_models/hod_factory.py
halotools/empirical_models/mock_factory.py
halotools/empirical_models/test_empirical_models/test_mock_factory.py

Changed default behavior of mock-making

---

halotools/sim_manager/generate_random_sim.py

Primarily useful for the test suite.

Working version of FakeMock

---

docs/managing_catalogs/sim_manager_step_by_step.rst
docs/managing_catalogs/supported_sim_list.rst
docs/overview.rst
docs/tutorials/raw_halocats.ipynb
docs/tutorials/raw_halocats.rst
docs/tutorials/using_halocat_binaries.ipynb
docs/tutorials/using_halocat_binaries.rst
halotools/sim_manager/cache_config.py
halotools/sim_manager/read_nbody.py
halotools/sim_manager/supported_sims.py
scripts/convert_tutorials.py
scripts/sim_manager_script.py

Two tutorials on how to use the sim_manager are now complete.

Documentation edits

---

halotools/empirical_models/hod_components.py

This addresses Issue #72 raised by @andrew-zentner

Changed param_dict to input_param_dict in OccupationComponent

---

halotools/utils/array_utils.py

See halotools.utils.array_utils for the randomly_downsample_data method

Added in random downsampler

---

docs/managing_catalogs/sim_manager_api.rst
halotools/utils/__init__.py
halotools/utils/array_utils.py
halotools/utils/spherical_geometry.py
halotools/utils/table_utils.py
halotools/utils/tests/test_table_utils.py

See the SampleSelector class in utils/table_utils.py

Added new module dedicated to halo/galaxy catalog manipulation 

---

halotools/utils/aggregation.py
halotools/utils/tests/test_aggregation.py

This is the old module converted to use astropy tables.

added aggregation module

---

halotools/utils/aggregation.py

fixed small bugs in aggregation module

---

halotools/sim_manager/cache_config.py
halotools/sim_manager/tests/test_cached_simulations.py

Implemented decorator to permit test suite functions to access the cache directory.

Cache testing

---

halotools/mock_observables/clustering.py

I fixed a bug in the redshift space tpcf code.  
The volume for analytical randoms was too small by a factor of 2.  This has been fixed.  This bug propagated to the wp code, which calls the redshift space tpcf code.  
The doc string for the wp code has been fixed to show the pi_bins must be passed, not pi_max.  As far as I can tell, there is no way to only specify a pi_max.

clustering update

---

halotools/mock_observables/clustering.py
halotools/mock_observables/pair_counters/cpairs/cpairs.pyx

This has some bug fixes for the clustering module, and updates to the doc strings.
This merge had some conflicts with the master, arising from doc strings edits by @aphearin , which I resolved, but this may make the merge into the halotools master complicated.

changes and updates to clustering module.

---

halotools/mock_observables/clustering.py

There were lots of errors in there.  I also added some notes to various functions.

cleaned up clustering doc strings

---

halotools/empirical_models/mock_factories.py

Now using try-except to load the ptcl_table when instantiating a mock

---

halotools/custom_exceptions.py
halotools/empirical_models/mock_factories.py
halotools/empirical_models/model_factories.py
halotools/sim_manager/catalog_manager.py
halotools/sim_manager/read_nbody_ascii.py
halotools/sim_manager/supported_sims.py
halotools/sim_manager/tests/test_supported_sims.py

Various bug fixes related to automated behavior of high-redshift catalog loading.

Bug fixes for loading high-redshift halo catalogs

---

halotools/empirical_models/mock_factories.py

Implemented number_density @property to mock factory

---

halotools/empirical_models/assembias.py
halotools/empirical_models/model_defaults.py
halotools/empirical_models/preloaded_hod_blueprints.py

Fixed a few bugs in Hearin15 constructor calls. Cleaned up init of the HeavisideAssembias class, resolving #146

Hearin15 cleanup

---

README.md
halotools/sim_manager/catalog_manager.py
halotools/sim_manager/supported_sims.py

Hopefully this will fix the RTD build problem

Tried embedding all h5py imports inside try...except 

---

docs/rtd-pip-requirements

Let's see how this goes. 
@eteq  - if the docs don't build after this, I'll raise an Issue on h5py.

Added h5py back into the docs/rtd-pip-requirements

---

halotools/empirical_models/model_helpers.py

Incomplete gamma function

---

halotools/mock_observables/clustering.py

Resolves #169 
CC @kilianbreathnach

Fixed bug in downsampling during tpcf autocorrelations for npts>1e6

---

halotools/empirical_models/model_defaults.py
halotools/empirical_models/phase_space_models.py

mc_generate_phase_space_points function added to NFWPhaseSpace class. 
This is purely a convenience function for returning a data table of points in NFW phase space.

Convenience function for generating points in NFW phase space

---

docs/function_usage/empirical_model_factory_functions.rst

Just need to mirror the pattern that fixed the phase space models problem

Fixed bug that was causing the factories not to render

---

docs/full_ref_api/halotools_full_api.rst
docs/usage_tutorials/mock_observables/angular_tpcf_usage_tutorial.rst
docs/usage_tutorials/mock_observables/marked_tpcf_usage_tutorial.rst
halotools/mock_observables/__init__.py
halotools/mock_observables/angular_tpcf.py
halotools/mock_observables/clustering_helpers.py
halotools/mock_observables/delta_sigma.py
halotools/mock_observables/groups.py
halotools/mock_observables/marked_tpcf.py
halotools/mock_observables/pair_counters/double_tree_helpers.py
halotools/mock_observables/pair_counters/double_tree_pairs.py
halotools/mock_observables/pair_counters/marked_double_tree_pairs.py
halotools/mock_observables/s_mu_tpcf.py
halotools/mock_observables/tpcf_jackknife.py
halotools/utils/spherical_geometry.py

General update of the mock observable module--doc strings, bug fixes, and adding w(theta) function.
*added angular two point correlation function 
*updated doc mock_observable doc strings (no compiling warnings on my machine)
*modified the pair counters to allow counting of all pairs beyond Lbox/3.0 w/o PBCs

update to mock_observables

---

halotools/mock_observables/marked_tpcf.py

These were in the marked_tpcf docstring. Now checking to see if this resolves the Travis failure.

Added a few blank lines where sphinx was complaining 

---

halotools/sim_manager/catalog_manager.py

I'm pretty sure the use if ``raise`` with a string wasn't intended and is a holdover from before there was a `HalotoolsError `.  But at any rate, raising strings doesn't work anymore anyway, so this fixes that.

switch catalog_manager exceptions to raising an exception instead of strings

---

docs/install.rst

There were some typos, and the sequence has been rearranged.

Improve installation guide

---

docs/quickstart_and_tutorials/mock_making/overview.rst
docs/quickstart_and_tutorials/mock_observations/mock_observables_api.rst
docs/quickstart_and_tutorials/mock_observations/overview.rst
docs/quickstart_and_tutorials/model_building/composing_models/abunmatch_model_factory_overview.rst
docs/quickstart_and_tutorials/model_building/composing_models/index.rst
docs/quickstart_and_tutorials/model_building/models_from_scratch/index.rst
docs/quickstart_and_tutorials/model_building/preloaded_models/index.rst
docs/quickstart_and_tutorials/quickstart_guides/halo_catalog_analysis_quickstart.rst
docs/quickstart_and_tutorials/quickstart_guides/mock_observables_quickstart.rst

Mostly just replaced partially-written and/or confusingly-written sections with "Tutorial coming soon!", and also did some slight restructuring.

Cleaned up obsolete and unfinished sections of the documentation

---

halotools/empirical_models/sfr_models/sfr_components.py

Fixed a few bugs in the sfr_components.

Interpol model bugfix

---

halotools/empirical_models/factories/mock_factory_template.py

Resolves #317 
CC @changhoonhahn, @mjvakili

Added num_threads feature to mock factory functions

---

docs/quickstart_and_tutorials/model_building/preloaded_models/hearin15_composite_model.rst
docs/quickstart_and_tutorials/model_building/preloaded_models/leauthaud11_composite_model.rst
docs/quickstart_and_tutorials/model_building/preloaded_models/zheng07_composite_model.rst
halotools/empirical_models/assembias_models/heaviside_assembias.py
halotools/empirical_models/composite_models/hod_models/hearin15.py
halotools/empirical_models/occupation_models/leauthaud11_components.py
halotools/utils/table_utils.py

* Added tutorial for the Hearin15 composite model.
* Added descriptions of all model parameters to the leauthaud11 and zheng07 tutorials. 
* Fixed a minor bug in compute_conditional_percentiles.

Hearin15 composite model tutorial

---

halotools/empirical_models/component_model_templates/binary_galprop_models.py
halotools/empirical_models/component_model_templates/tests/test_binary_galprop_models.py
halotools/empirical_models/composite_models/sfr_models/smhm_binary_sfr.py
halotools/empirical_models/factories/subhalo_model_factory.py
halotools/empirical_models/factories/tests/test_subhalo_model_factory.py
halotools/empirical_models/sfr_models/halo_mass_quenching.py

Improved API and bounds checking of the binary galprop model

Binary galprop bugfix

---

halotools/sim_manager/user_supplied_halo_catalog.py

Minor improvements to docstring of the add_halocat_to_cache method of the UserSuppliedHaloCatalog
CC @duncandc

Improved docstring to UserSuppliedHaloCatalog

---

halotools/sim_manager/tabular_ascii_reader.py

If I'm understanding things correctly, this comment is backwards.

Correct doc for _get_fname() method.

---

docs/quickstart_and_tutorials/model_building/preloaded_models/behroozi10_composite_model.rst
docs/quickstart_and_tutorials/model_building/preloaded_models/hearin15_composite_model.rst
docs/quickstart_and_tutorials/model_building/preloaded_models/tinker13_composite_model.rst
halotools/empirical_models/assembias_models/heaviside_assembias.py
halotools/empirical_models/assembias_models/tests/test_assembias.py
halotools/empirical_models/component_model_templates/binary_galprop_models.py
halotools/empirical_models/component_model_templates/tests/test_binary_galprop_models.py
halotools/empirical_models/composite_models/hod_models/hearin15.py
halotools/empirical_models/composite_models/hod_models/tests/test_tinker13.py
halotools/empirical_models/composite_models/hod_models/tinker13.py
halotools/empirical_models/composite_models/sfr_models/smhm_binary_sfr.py
halotools/empirical_models/composite_models/smhm_models/behroozi10.py
halotools/empirical_models/factories/subhalo_model_factory.py
halotools/empirical_models/factories/tests/test_subhalo_model_factory.py
halotools/empirical_models/model_defaults.py
halotools/empirical_models/model_helpers.py
halotools/empirical_models/occupation_models/leauthaud11_components.py
halotools/empirical_models/occupation_models/tinker13_components.py
halotools/empirical_models/occupation_models/zheng07_components.py
halotools/empirical_models/phase_space_models/profile_models/tests/test_nfw_profile.py
halotools/empirical_models/sfr_models/halo_mass_quenching.py
halotools/empirical_models/smhm_models/behroozi10.py
halotools/empirical_models/smhm_models/moster13.py
halotools/empirical_models/smhm_models/scatter_models.py
halotools/empirical_models/smhm_models/smhm_model_template.py
halotools/empirical_models/smhm_models/tests/test_smhm_components.py

Corrected typos in abcissa

---

README.md

Implemented suggestion made by @texodus to include a few lines of basic syntax in the root-level README.

Update readme to include a basic code demo

---

halotools/sim_manager/fake_sim.py
halotools/sim_manager/tests/test_fake_sim.py

Modify default number of halos in FakeSim to reduce memory load of test suite

Minor modifications to FakeSim

---

halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/tests/test_mock_factories.py

The MockFactory template class now has a xyz_positions method that returns an ndarray of shape (Ngals, 3), the data structure used throughout mock_observables. 
Optional keywords support two features worthy of mention:
1. The input `mask` lets you pass in a boolean masking array to retrieve a subpopulatoin
2. The input `velocity_distortion_dimension` lets you apply redshift-space distortions to any of the three cartesian directions.

Add convenience function in mock_observables for retrieving the xyz positions of a table

---

halotools/utils/aggregation.py
halotools/utils/halocat_utils.py
halotools/utils/table_utils.py
halotools/utils/tests/test_aggregation.py

Fixed a few unnecessary imports, deleted some commented-out code.

Minor bug-fixes to utils subpackage

---

halotools/utils/__init__.py
halotools/utils/tests/test_value_added_halo_table_functions.py
halotools/utils/value_added_halo_table_functions.py

Add 'broadcast_host_halo_property', 'add_halo_hostid' functions to the value_added_halo_table_functions module.

Add convenience wrapper functions around the aggregation module

---

docs/quickstart_and_tutorials/tutorials/catalog_analysis/galcat_analysis/galaxy_catalog_analysis_tutorial1.rst

A few clarifications and corrections. Very minor PR.

Corrected a few errors in tutorial1

---

halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/tests/test_mock_factories.py
halotools/mock_observables/catalog_analysis_helpers.py
halotools/mock_observables/tests/test_catalog_analysis_helpers.py

Moved xyz_positions into a stand-alone catalog_analysis_helpers function. This way users not using mock population can use this function.

refactored the xyz_positions bundling function

---

halotools/mock_observables/catalog_analysis_helpers.py

Related to in-place manipulations of an array that was never copied

Fixed bug in return_xyz_formatted_array 

---

halotools/mock_observables/angular_tpcf.py
halotools/utils/distances.py

fixes bug in angular_tpcf.py randoms calculation.  
also adds support for using a single float for the period parameter in utils.distances.py module.

Mock obs devel

---

halotools/empirical_models/factories/subhalo_model_factory.py
halotools/empirical_models/factories/tests/test_hod_model_factory.py
halotools/empirical_models/factories/tests/test_subhalo_model_factory.py

Minor adjustments to SubhaloModelFactory internals and improvement of test suite of both model factories.

Improve testing of model factories

---

halotools/empirical_models/occupation_models/occupation_model_template.py
halotools/empirical_models/occupation_models/tests/test_occupation_component.py

Minor adjustments to OccupationComponent and test suite to improve generality and coverage

Update to OccupationComponent class

---

appveyor.yml
halotools/mock_observables/clustering_helpers.py
halotools/mock_observables/pair_counters/test_pair_matrices/test_pair_matrix.py
halotools/utils/array_utils.py

Committing an empty configuration file for appveyor

Add empty appveyor.yml file to repo

---

docs/quickstart_and_tutorials/managing_catalogs/supported_sim_list.rst
docs/quickstart_and_tutorials/quickstart_guides/working_with_halotools_provided_catalogs.rst
halotools/sim_manager/cached_halo_catalog.py
halotools/sim_manager/download_manager.py

Thanks to @cwhite1026 for the suggestion to improve discoverability by including a table of options. This PR resolves @390.

Improved documentation of which snapshots are available for download

---

halotools/sim_manager/rockstar_hlist_reader.py

This PR addresses #409. @duncandc - thanks for the suggestion, let me know if you think this is still difficult to follow.

Improved docstring to RockstarHlistReader

---

docs/quickstart_and_tutorials/development/bug_reports.rst
docs/quickstart_and_tutorials/development/citing_halotools.rst
docs/quickstart_and_tutorials/development/features_planned_for_next_release.rst
docs/quickstart_and_tutorials/development/index.rst
docs/quickstart_and_tutorials/development/making_contributions.rst
docs/quickstart_and_tutorials/index.rst

Added documentation for submitting a bug report and also a planned-features page

Minor documentation improvements

---

halotools/mock_observables/void_stats.py

These had become out of date and are now correct.

Add corrections to the vpf and upf docstring

---

halotools/mock_observables/pair_counters/double_tree_pairs.py

@a-kravtsov - since you have been looking at this code most recently, would mind vetting these documentation improvements and providing feedback on whether this is sufficiently clear, or if further clarification is warranted?

Improved docstrings of pair-counters in the double_tree_pairs module

---

halotools/mock_observables/tests/test_delta_sigma.py

Function correctness still remains to be tested for simple inputs, but this at least covers basic input-output.

Added unit-test of delta_sigma

---

halotools/mock_observables/mock_survey.py
halotools/mock_observables/test_clustering/test_wp.py
halotools/mock_observables/wp.py

API of wp altered.
ra_dec_z code bug fix.

mock observables bug fixes and API alteration

---

halotools/mock_observables/isolation_criteria.py
halotools/mock_observables/pair_counters/double_tree_pair_matrix.py
halotools/mock_observables/tests/test_isolation_criteria.py

Added extensive unit-testing of isolation_criteria module and fixed bugs revealed by the testing .
This PR resolves #291.

Bugfixes to isolation_criteria module

---

halotools/mock_observables/wp.py
halotools/utils/group_member_generator.py

Fixed bugs in docstrings for wp and group_member_generator, resolving #449 and #448 .

Docstring edits

---

docs/quickstart_and_tutorials/development/contributors.rst

Added @rainwoodman for help with mock_observables optimization and @yyao for help with abundance matching

Updated contributor list

---

halotools/mock_observables/catalog_analysis_helpers.py

@andrew-zentner - let me know if this clear enough or if it could still be improved.

Improved docstring of return_xyz_formatted_array 

---

scripts/download_additional_halocat.py
scripts/download_initial_halocat.py

I've added arguments to store catalogs in a variable location to the startup scripts.

Added variable directory argument to helper scripts.

---

halotools/conftest.py

Minor update to get more info out of the test runs.
Also there are quite a few deprecation warnings, sooner or later those should be taken care of as well. Examples are here: https://travis-ci.org/bsipocz/halotools/jobs/120486330

Conftest update

---

halotools/mock_observables/tpcf.py
halotools/mock_observables/wp.py

@manodeep - since I'm hard-coding the URL to your repo into my wp and tpcf docstrings, please keep me abreast of any change to your code's home.

Added citations to Corrfunc code

---

halotools/mock_observables/clustering_helpers.py
halotools/mock_observables/error_estimation_tools.py
halotools/mock_observables/groups.py
halotools/mock_observables/isolation_criteria.py
halotools/mock_observables/large_scale_density.py
halotools/mock_observables/marked_tpcf.py
halotools/mock_observables/nearest_neighbor.py
halotools/mock_observables/pair_counters/double_tree.py
halotools/mock_observables/pair_counters/double_tree_pair_matrix.py
halotools/mock_observables/pair_counters/pairs.py
halotools/mock_observables/rp_pi_tpcf.py
halotools/mock_observables/s_mu_tpcf.py
halotools/mock_observables/tpcf_estimators.py

Fixed a few bugs, docstring errors and PEP8 style issues in mock_observables

Docstring edits and PEP8 issues

---

CHANGES.rst
halotools/mock_observables/__init__.py
halotools/mock_observables/angular_tpcf.py
halotools/mock_observables/delta_sigma.py
halotools/mock_observables/pair_counters/__init__.py
halotools/mock_observables/pair_counters/cpairs/__init__.py
halotools/mock_observables/pair_counters/cpairs/npairs_jackknife_3d_engine.pyx
halotools/mock_observables/pair_counters/cpairs/npairs_projected_engine.pyx
halotools/mock_observables/pair_counters/cpairs/npairs_s_mu_engine.pyx
halotools/mock_observables/pair_counters/cpairs/npairs_xy_z_engine.pyx
halotools/mock_observables/pair_counters/cpairs/setup_package.py
halotools/mock_observables/pair_counters/mesh_helpers.py
halotools/mock_observables/pair_counters/npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/npairs_projected.py
halotools/mock_observables/pair_counters/npairs_s_mu.py
halotools/mock_observables/pair_counters/npairs_xy_z.py
halotools/mock_observables/pair_counters/rectangular_mesh.py
halotools/mock_observables/pair_counters/test_pair_counters/test_mesh_helpers.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_projected.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_s_mu.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_rectangular_mesh.py
halotools/mock_observables/rp_pi_tpcf.py
halotools/mock_observables/s_mu_tpcf.py
halotools/mock_observables/tpcf.py
halotools/mock_observables/tpcf_estimators.py
halotools/mock_observables/tpcf_jackknife.py
halotools/mock_observables/tpcf_multipole.py
halotools/mock_observables/wp.py

Added new pair counting engines to Halotools, improving performance of unmarked pair counting by 30%-50x, depending on the numerical regime.

New npairs engines

---

halotools/mock_observables/pair_counters/test_pair_counters/pure_python_distance_matrix.py
halotools/mock_observables/pair_counters/test_pair_counters/test_pairwise_distance_3d.py

Added brute force testing of the pairwise_distance algorithms that drive FoFGroups

Test pairwise distances

---

docs/quickstart_and_tutorials/getting_started_overview.rst
halotools/mock_observables/angular_tpcf.py
halotools/mock_observables/marked_tpcf.py
halotools/mock_observables/pair_counters/cpairs/npairs_xy_z_engine.pyx
halotools/mock_observables/pair_counters/cpairs/pairwise_distance_3d_engine.pyx
halotools/mock_observables/pair_counters/cpairs/pairwise_distance_xy_z_engine.pyx
halotools/mock_observables/pair_counters/cpairs/pairwise_distances.pyx
halotools/mock_observables/pair_counters/marked_cpairs/conditional_pairwise_distances.pyx
halotools/mock_observables/pair_counters/marked_cpairs/marked_npairs_xy_z_engine.pyx
halotools/mock_observables/pair_counters/marked_cpairs/velocity_marked_npairs_xy_z_engine.pyx
halotools/mock_observables/pair_counters/marked_npairs_3d.py
halotools/mock_observables/pair_counters/marked_npairs_xy_z.py
halotools/mock_observables/pair_counters/pairs.py
halotools/mock_observables/pair_counters/pairwise_distance_3d.py
halotools/mock_observables/pair_counters/velocity_marked_npairs_3d.py
halotools/mock_observables/pair_counters/velocity_marked_npairs_xy_z.py
halotools/mock_observables/pairwise_velocity_stats.py
halotools/mock_observables/s_mu_tpcf.py
halotools/mock_observables/tpcf.py
halotools/mock_observables/tpcf_one_two_halo_decomp.py
halotools/utils/autosummary_workaround.py

Updated installation instructions, resolving #461.

Install instructions update

---

halotools/utils/crossmatch.py

The docstring now has clearer language and Astropy Table-based examples, thanks to feedback from @taldcroft and @eteq. 
@taldcroft - the docstring examples are chosen to be simple and do not necessarily demonstrate how the algorithm has a different use-case from `table.join`. To see the difference, the simplest place to look is Example 2 of the halo catalog analysis tutorial.

Improved docstring of crossmatch function

---

halotools/utils/value_added_halo_table_functions.py

The `crossmatch` function is very heavily optimized and is in general much faster than `group_member_generator` since all loops in `crossmatch` are performed in the compiled C code of Numpy. Since `group_member_generator` was being used to add host halo properties during the initial call to CachedHaloCatalog, this change improves the runtime of loading a halo catalog improves by another 2x, resolving #515. 
CC @duncandc - I think you'll find halo catalogs to load in a more acceptable time now, but let me know if you still find this annoying slow.

Changed broadcast_host_halo_property algorithm to be based on crossmatch

---

halotools/empirical_models/composite_models/tests/test_preloaded_models.py
halotools/empirical_models/phase_space_models/profile_models/tests/test_halo_catalog_nfw_consistency.py
halotools/empirical_models/phase_space_models/profile_models/tests/test_nfw_profile.py
halotools/empirical_models/phase_space_models/profile_models/tests/test_profile_helpers.py
halotools/mock_observables/pair_counters/test_pair_counters/test_marked_npairs_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_marked_npairs_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_projected.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_s_mu.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_pairwise_distance_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_rectangular_mesh.py
halotools/mock_observables/radial_profiles/tests/test_radial_profile_3d.py
halotools/mock_observables/tests/test_mock_observables_helpers.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf_one_two_halo.py

to be consistent with the rest of the test files and mainly to make it possible to run the tests without a local pytest install.

Importing pytest from astropy

---

halotools/mock_observables/pairwise_velocities/mean_radial_velocity_vs_r.py
halotools/mock_observables/pairwise_velocities/pairwise_velocities_helpers.py
halotools/mock_observables/pairwise_velocities/tests/test_pairwise_velocity_helpers.py
halotools/mock_observables/pairwise_velocities/tests/test_pairwise_velocity_stats.py
halotools/mock_observables/pairwise_velocities/tests/test_velocity_marked_npairs_3d.py
halotools/mock_observables/pairwise_velocities/velocity_marked_npairs_3d.py

This PR improves the testing of the `pairwise_velocities` sub-package.

Pairwise velocity testing

---

halotools/sim_manager/user_supplied_halo_catalog.py

As requested by @duncandc, Astropy Table objects storing an existing halo catalog can now be trivially transformed into a `UserSuppliedHaloCatalog`, with an explicit demonstration in the docstring.

UserSuppliedHaloCatalog from Astropy Table

---

README.md
docs/function_usage/index.rst
docs/function_usage/mock_observables_functions.rst
docs/function_usage/utility_functions.rst
docs/install.rst
docs/installing_halotools_with_virtualenv.rst
halotools/sim_manager/rockstar_hlist_reader.py

Updated Functions Grouped by Category section, installation instructions and README. This PR completes development of v0.2.

Func doc groupings

---

setup.py

Changed formatting of setup.py to be consistent with the rest of the package

setup.py formatting

---

halotools/mock_observables/two_point_clustering/delta_sigma.py
halotools/mock_observables/two_point_clustering/wp.py
halotools/sim_manager/halo_table_cache.py
halotools/sim_manager/ptcl_table_cache.py

This PR adds new commits to #544, and will supersede it. The first commit began from #544, and an additional commit afee2cdd57144d19f9730f767ae239835bb63a9d resolved the Travis failure that occurred for entirely unrelated reasons (due to a change in the development branch of astropy). 
See #544 for a discussion of the bug fix related to `delta_sigma`.

`delta_sigma` bugfix + Astropy deprecation bugfix

---

README.md
docs/install.rst

This PR modifies the documentation to resolve #564.

Installation instructions

---

scripts/download_additional_halocat.py
scripts/download_initial_halocat.py

Download script bugfix

---

halotools/empirical_models/occupation_models/leauthaud11_components.py

fixed bug in documentation of Leauthaud11Sats

---

docs/quickstart_and_tutorials/development/citing_halotools.rst
halotools/sim_manager/cached_halo_catalog.py
halotools/sim_manager/supported_sims.py

Added citation information to CachedHaloCatalog objects

---

docs/install.rst
docs/installation_troubleshooting.rst
docs/installing_halotools_with_virtualenv.rst

Created a new page to store "known issues" with installation, e.g. #561 and #447.

Added installation troubleshooting section to docs

---

halotools/sim_manager/fake_sim.py
halotools/sim_manager/tests/test_fake_sim.py
halotools/utils/tests/test_value_added_halo_table_functions.py
halotools/utils/value_added_halo_table_functions.py

Added halo_mvir_host_halo column to FakeSim halo_table

---

halotools/mock_observables/catalog_analysis_helpers.py
halotools/mock_observables/tests/test_catalog_analysis_helpers.py

Function returns +/- 1 depending on whether x2 > x1, accounting for PBCs.

Added sign function and unit-testing into catalog_analysis_helpers.py

---

halotools/mock_observables/pair_counters/cpairs/npairs_per_object_3d_engine.pyx
halotools/mock_observables/pair_counters/npairs_per_object_3d.py

Fixed docstring for npairs_per_object_3d and its engine

---

CHANGES.rst
halotools/mock_observables/pair_counters/cpairs/npairs_per_object_3d_engine.pyx
halotools/mock_observables/pair_counters/npairs_per_object_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/pure_python_npairs_per_object_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_per_object_3d.py
halotools/utils/array_utils.py

This PR resolves the indexing error raised in #606.

Bugfix for npairs_per_object_3d

---

halotools/empirical_models/smhm_models/tests/test_smhm_components.py
halotools/mock_observables/pair_counters/cpairs/pairwise_distance_3d_engine.pyx
halotools/mock_observables/pair_counters/cpairs/pairwise_distance_xy_z_engine.pyx
halotools/mock_observables/pair_counters/pairwise_distance_3d.py
halotools/mock_observables/pair_counters/pairwise_distance_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_pairwise_distance_3d.py

This pull requests resolves issue #599.  
We need more testing for pairwise distance matrix.

r_max can be an array

---

CHANGES.rst
halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/tests/test_hod_mock_factory.py

This PR resolves #574. Thanks for making this easy by writing a good docstring, @johannesulf.

Added estimate_ngals feature to HodMockFactory class.

---

docs/quickstart_and_tutorials/managing_catalogs/supported_sim_list.rst

Fixed link to bolshoi-planck catalogs

---

halotools/mock_observables/pair_counters/cpairs/npairs_s_mu_engine.pyx

Main change is `from libc.math cimport sqrt`

Cleaned s_mu_engine of python layer 

---

halotools/utils/array_utils.py
halotools/utils/spherical_geometry.py
halotools/utils/value_added_halo_table_functions.py

This PR serves the dual purpose of slightly improving testing of the `utils` sub-package, and also triggers one final CI build before the `v0.4` release, for example to catch any possible last-minute deprecation warnings.

Added some doctests to utils functions

---

halotools/mock_observables/group_identification/fof_groups.py

This PR improves the user-interface of the FoFGroups class by making automatic the call to the create_graph() method, as needed.

FoFGroups bug fix

---

halotools/empirical_models/composite_models/hod_models/tests/test_zheng07.py
halotools/empirical_models/composite_models/hod_models/zheng07.py

This was resolved by simply propagating the forgotten keyword argument modulate_with_cenocc=modulate_with_cenocc through to Zheng07Sats, resolving #646.

Resolved Zheng07Sats ``modulate_with_cenocc`` bug

---

halotools/empirical_models/factories/hod_model_factory.py
halotools/empirical_models/factories/tests/test_hod_model_factory.py

This PR resolves the feature request made in #643. 
@kilianbreathnach - I'm done unit-testing this, but would you try it out for the specific use-case that led to #643 and let me know how it goes?

Add support for a ``redshift`` keyword argument to the HodModelFactory

---

halotools/sim_manager/download_manager.py

This PR addresses issue #628. It corrects the documentation of the DownloadManager and changes nothing about the code itself.

Fixed documentation for DownloadManager

---

CHANGES.rst
halotools/mock_observables/pair_counters/npairs_per_object_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_per_object_3d.py

Bugfix for multi-threaded npairs_per_object_3d calculation

---

.travis.yml
halotools/utils/__init__.py
halotools/utils/inverse_transformation_sampling.py
halotools/utils/tests/test_its.py
halotools/utils/tests/test_table_utils.py

New module provides a simple interpolation-based framework for inverse transformation sampling.

Added inverse transformation sampling module

---

.travis.yml

Updated Numpy version to 1.11 for python 3.3 in .travis.yml

---

docs/function_usage/abundance_matching.rst
docs/function_usage/index.rst
halotools/empirical_models/abunmatch/conditional_abunmatch.py

Minor improvements to documentation

Documentation cleanup

---

docs/function_usage/phase_space_models_functions.rst
docs/function_usage/utility_functions.rst
docs/quickstart_and_tutorials/development/citing_halotools.rst
docs/source_notes/index.rst
halotools/utils/array_utils.py

Minor updates to documentation

Doc updates

---

halotools/mock_observables/two_point_clustering/delta_sigma.py

Thanks to @sssaito for pointing out that the `delta_sigma` function normalization should include an additional factor of cosmology.Onu0

Fixed bug in delta_sigma calculation 

---

CHANGES.rst
halotools/empirical_models/composite_models/hod_models/tests/test_tinker13.py
halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/subhalo_mock_factory.py
halotools/empirical_models/phase_space_models/monte_carlo_helpers.py
halotools/empirical_models/phase_space_models/nfw_phase_space.py
halotools/empirical_models/phase_space_models/tests/test_nfw_phase_space.py

@johannesulf - if you could do the science verification with this PR, that would be much appreciated.

Resolved buggy behavior due to incorrect treatment of random number seed

---

CHANGES.rst
docs/function_usage/mock_observables_functions.rst
halotools/mock_observables/__init__.py
halotools/mock_observables/occupation_stats.py
halotools/mock_observables/tests/test_occupation_stats.py

Added convenience function to calculate the Hod

---

docs/function_usage/index.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/cacciato09_composite_model.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/index.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/preloaded_models_list.rst
halotools/empirical_models/composite_models/hod_models/__init__.py
halotools/empirical_models/composite_models/hod_models/cacciato09.py
halotools/empirical_models/factories/prebuilt_model_factory.py
halotools/empirical_models/model_helpers.py
halotools/empirical_models/occupation_models/__init__.py
halotools/empirical_models/occupation_models/cacciato09_components.py
halotools/empirical_models/occupation_models/engines/__init__.py
halotools/empirical_models/occupation_models/engines/cacciato09_sats_mc_prim_galprop_engine.pyx
halotools/empirical_models/occupation_models/engines/setup_package.py
halotools/empirical_models/occupation_models/tests/test_cacciato09_clf.py

This PR introduces the Cacciato et al. (2009) CLF composite model. Addresses #665.

Cacciato09 Conditional Luminosity Function

---

halotools/mock_observables/pair_counters/cpairs/distances.pyx
halotools/mock_observables/pair_counters/marked_cpairs/distances.pyx
halotools/mock_observables/pair_counters/marked_cpairs/marking_functions.pyx

Eliminated calls to numpy functions within C-defined functions in cython

---

halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/hod_model_factory.py
halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/model_factory_template.py
halotools/empirical_models/factories/subhalo_mock_factory.py
halotools/empirical_models/factories/subhalo_model_factory.py

Improved documentation on model.populate_mock vs. mock.populate

---

CHANGES.rst

`Changes.rst` is now up-to-date with all significant changes since the last release, in preparation for the soon-to-be-released `v0.5`

Updated changelog 

---

docs/conf.py
docs/source_notes/convert_tutorials.py
ez_setup.py
halotools/empirical_models/composite_models/hod_models/tests/test_zheng07.py
halotools/empirical_models/occupation_models/cacciato09_components.py
halotools/empirical_models/phase_space_models/subhalo_based_models/subhalo_phase_space.py
halotools/empirical_models/phase_space_models/tests/test_nfw_phase_space.py
halotools/mock_observables/occupation_stats.py
halotools/mock_observables/pair_counters/mesh_helpers.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_per_object_3d.py
halotools/mock_observables/tests/test_occupation_stats.py
halotools/sim_manager/tests/test_supported_sims.py
halotools/sim_manager/tests/test_user_supplied_halo_catalog.py
scripts/convert_documentation_tutorials.py
scripts/download_additional_halocat.py
scripts/download_initial_halocat.py
scripts/rebuild_halo_table_cache_log.py
scripts/rebuild_ptcl_table_cache_log.py
setup.py

Fixed all appearances of the following errors that do not appear inside astropy_helpers:
```
E124, E127, W391, E265, W503, E122, E203, E225, E266, E303
```

Resolved PEP8 syntax violations 

---

docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/cacciato09_composite_model.rst

Updated documentation

---

CHANGES.rst
docs/function_usage/index.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/index.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/preloaded_models_list.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/zu_mandelbaum15_composite_model.rst
halotools/empirical_models/composite_models/hod_models/__init__.py
halotools/empirical_models/composite_models/hod_models/zheng07.py
halotools/empirical_models/composite_models/hod_models/zu_mandelbaum15.py
halotools/empirical_models/composite_models/tests/test_preloaded_models.py
halotools/empirical_models/factories/prebuilt_model_factory.py
halotools/empirical_models/occupation_models/__init__.py
halotools/empirical_models/occupation_models/leauthaud11_components.py
halotools/empirical_models/occupation_models/tests/test_zu_mandelbaum15_components.py
halotools/empirical_models/occupation_models/zu_mandelbaum15_components.py
halotools/empirical_models/smhm_models/__init__.py
halotools/empirical_models/smhm_models/behroozi10.py
halotools/empirical_models/smhm_models/zu_mandelbaum15.py

This PR introduces the Zu & Mandelbaum HOD model fit to z=0 SDSS clustering and lensing.

Added Zu & Mandelbaum (2015) HOD model for M*-threshold samples

---

CHANGES.rst
docs/function_usage/index.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/index.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/preloaded_models_list.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/zu_mandelbaum16_composite_model.rst
halotools/empirical_models/composite_models/hod_models/__init__.py
halotools/empirical_models/composite_models/hod_models/tests/test_zu_mandelbaum16.py
halotools/empirical_models/composite_models/hod_models/zu_mandelbaum16.py
halotools/empirical_models/factories/prebuilt_model_factory.py
halotools/empirical_models/factories/tests/test_hod_mock_factory.py
halotools/empirical_models/factories/tests/test_prebuilt_hod_model_factory.py
halotools/empirical_models/sfr_models/__init__.py
halotools/empirical_models/sfr_models/tests/test_zu_mandelbaum16.py
halotools/empirical_models/sfr_models/zu_mandelbaum16.py

This PR includes a new prebuilt HOD model and accompanying tutorials.

Added Zu & Mandelbaum (2016) HOD model

---

README.md
docs/usage_tutorials/empirical_models/subhalo_phase_space/subhalo_phase_space_tutorial.rst
halotools/empirical_models/phase_space_models/subhalo_based_models/__init__.py
halotools/empirical_models/phase_space_models/subhalo_based_models/subhalo_phase_space.py
halotools/empirical_models/phase_space_models/subhalo_based_models/tests/test_subhalo_phase_space.py

Added documentation on how to use SubhaloPhaseSpace class to populate HOD satellites by placing them on top of subhalos

Subhalo phase space tutorial

---

halotools/mock_observables/surface_density/tests/external_delta_sigma.py
halotools/mock_observables/surface_density/tests/pure_python_weighted_npairs_xy.py
halotools/mock_observables/surface_density/tests/test_pure_python_weighted_npairs_xy.py

This is just a place holder PR. Once this is merged in, @surhudm can submit what I think will be a simple copy-and-paste PR of the `external_delta_sigma` function using the appropriate package structure whenever getting the chance. That function will be used to resolve #547.

Skeleton of new surface_density sub-package

---

halotools/empirical_models/occupation_models/cacciato09_components.py

Fix central occupation component initialization of Cacciato09Sats

---

halotools/mock_observables/pair_counters/__init__.py
halotools/mock_observables/pair_counters/mesh_helpers.py
halotools/mock_observables/pair_counters/rectangular_mesh_2d.py
halotools/mock_observables/surface_density/engines/__init__.py
halotools/mock_observables/surface_density/engines/setup_package.py
halotools/mock_observables/surface_density/engines/weighted_npairs_xy_engine.pyx
halotools/mock_observables/surface_density/mass_in_cylinders.py
halotools/mock_observables/surface_density/surface_density.py
halotools/mock_observables/surface_density/surface_density_helpers.py
halotools/mock_observables/surface_density/tests/test_mass_in_cylinders.py
halotools/mock_observables/surface_density/tests/test_surface_density.py
halotools/mock_observables/surface_density/tests/test_surface_density_helpers.py
halotools/mock_observables/surface_density/tests/test_weighted_npairs_xy.py
halotools/mock_observables/surface_density/weighted_npairs_xy.py
halotools/mock_observables/tests/cf_helpers.py
halotools/sim_manager/fake_sim.py

Added new pair-counters that work entirely in two dimensions, as well as several functions in the new surface_density sub-package that will be used to calculate galaxy-galaxy lensing

Two dim functionality

---

halotools/mock_observables/pair_counters/cpairs/npairs_per_object_3d_engine.pyx
halotools/mock_observables/surface_density/engines/__init__.py
halotools/mock_observables/surface_density/engines/setup_package.py
halotools/mock_observables/surface_density/engines/weighted_npairs_per_object_xy_engine.pyx
halotools/mock_observables/surface_density/mass_in_cylinders.py
halotools/mock_observables/surface_density/tests/pure_python_weighted_npairs_per_object_xy.py
halotools/mock_observables/surface_density/tests/pure_python_weighted_npairs_xy.py
halotools/mock_observables/surface_density/tests/test_mass_in_cylinders.py
halotools/mock_observables/surface_density/tests/test_weighted_npairs_per_object_xy.py
halotools/mock_observables/surface_density/tests/test_weighted_npairs_xy.py
halotools/mock_observables/surface_density/weighted_npairs_per_object_xy.py
halotools/mock_observables/surface_density/weighted_npairs_xy.py

New functions calculate the number of pairs per object in 2d, for eventual use with pre-computing the galaxy-galaxy lensing signal

Npairs xy per object

---

halotools/mock_observables/surface_density/tests/external_delta_sigma.py

This pull request provides an external delta sigma module in order to test the surface density package currently in development.

Added external delta sigma module

---

halotools/mock_observables/surface_density/__init__.py
halotools/mock_observables/surface_density/delta_sigma.py
halotools/mock_observables/surface_density/mass_in_cylinders.py
halotools/mock_observables/surface_density/tests/test_delta_sigma.py

New function allows users to calculate galaxy-galaxy lensing after pre-computing the galaxy-mass counts-in-cylinders

Added delta_sigma_from_precomputed_pairs function

---

halotools/empirical_models/factories/subhalo_model_factory.py
halotools/empirical_models/factories/tests/test_hod_model_factory.py
halotools/empirical_models/factories/tests/test_subhalo_model_factory.py
halotools/mock_observables/pair_counters/pairs.py
halotools/sim_manager/tests/test_halo_table_cache.py
halotools/sim_manager/tests/test_ptcl_table_cache.py

Improved unit-testing coverage of exception-handling in several different modules across package

Testing coverage

---

halotools/mock_observables/surface_density/delta_sigma.py

Improved docstring of delta_sigma

---

halotools/empirical_models/composite_models/hod_models/tests/test_zu_mandelbaum16.py
halotools/empirical_models/factories/tests/test_hod_mock_factory.py
halotools/empirical_models/phase_space_models/tests/test_nfw_phase_space.py

Modified unit-test to reduce the memory load during test_zu_mandelbaum16 module

Reduce memory footprint of module testing Zu & Mandelbaum 2106 model

---

halotools/empirical_models/factories/hod_model_factory.py

fixed unhashable type error in sets of dicts

---

docs/whats_new.rst

Clarified comments on the new BiasedNFWPhaseSpace and SFRBiasedNFWPhaseSpace classes in the What's New? section of the docs

What's New? docs clarifications

---

halotools/sim_manager/rockstar_hlist_reader.py

Improved clarity of the docstring to the RockstarHlistReader

Docstring improvements to RockstarHlistReader

---

README.md

The badge shows the most recent version number of the code, added to the Installation section of the README.

Added pypi badge to README

---

halotools/utils/crossmatch.py

This pull request is meant to address issue #707 and the discussion on pull request #744.

A proposed fix to an ambiguity in the description of crossmatch() utility function

---

README.md
docs/install.rst
docs/whats_new.rst

Updated documentation to reflect v0.5 release

v0.5 release docs update

---

halotools/sim_manager/cached_halo_catalog.py
halotools/sim_manager/halo_table_cache_log_entry.py
halotools/sim_manager/ptcl_table_cache_log_entry.py
halotools/sim_manager/rockstar_hlist_reader.py
halotools/sim_manager/tests/test_supported_sims.py

This should help resolve #741 - Thanks to @mclaughlin6464 for pointing out this problem

Eliminated appearances of self.h5py

---

halotools/utils/group_member_generator.py

Corrected bug in group_member_generator docs

---

halotools/empirical_models/occupation_models/tests/test_cacciato09_clf.py

I added a test that compares the MC distribution of magnitude gaps between the brightest satellite and the central against the values in https://arxiv.org/abs/1207.5508 (Figure 1, log M = 14.5).

Added test for Cacciato09 CLF model, addressing #758

---

halotools/custom_exceptions.py
halotools/tests/ddc.py
halotools/tests/test_amurrica.py
halotools/tests/usa.py

Improved robustness of source code introspection tests

added a few new unit-tests of `mock_observables`

---

CHANGES.rst
docs/whats_new_history/whats_new_0.5.rst
docs/whats_new_history/whats_new_0.6.rst
docs/whats_new_history/whats_new_v0x_history.rst

There's now a section for the in-progress v0.6

Whats new docs update

---

docs/install.rst

Updated documentation to explicitly walk through how to resolve potential conflicts with previous installations.

Installation instruction update

---

README.md
docs/quickstart_and_tutorials/development/citing_halotools.rst

Updated citation section of docs and README with DOI citation information

Docs update

---

.travis.yml
setup.cfg

Now using tool:pytest, replacing deprecated pytest section

Updated setup.cfg

---

halotools/empirical_models/abunmatch/conditional_abunmatch.py
halotools/empirical_models/abunmatch/noisy_percentile.py
halotools/utils/inverse_transformation_sampling.py

Added cross-references, improved clarity of examples, and added reference to Jeremy Bailin's tutorial on inverse transformation sampling

Improved documentation of inverse transformation sampling

---

.travis.yml
halotools/conftest.py

Implemented workaround suggested by @bsipocz

Resolve PyOpenSSL DeprecationWarning issue

---

docs/source_notes/mock_observables/zspace_distortions.rst
halotools/mock_observables/catalog_analysis_helpers.py
halotools/mock_observables/tests/test_catalog_analysis_helpers.py

This has now been requested by a few people, so this PR includes a first-principles derivation of the implemented formula.

Added documentation deriving z-space distortion formula

---

CHANGES.rst
halotools/mock_observables/pair_counters/__init__.py
halotools/mock_observables/pair_counters/cpairs/__init__.py
halotools/mock_observables/pair_counters/cpairs/setup_package.py
halotools/mock_observables/pair_counters/cpairs/weighted_npairs_s_mu_engine.pyx
halotools/mock_observables/pair_counters/marked_npairs_3d.py
halotools/mock_observables/pair_counters/marked_npairs_xy_z.py
halotools/mock_observables/pair_counters/npairs_3d.py
halotools/mock_observables/pair_counters/npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/npairs_per_object_3d.py
halotools/mock_observables/pair_counters/npairs_projected.py
halotools/mock_observables/pair_counters/npairs_s_mu.py
halotools/mock_observables/pair_counters/npairs_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_weighted_npairs_s_mu.py
halotools/mock_observables/pair_counters/weighted_npairs_s_mu.py

PR resolves #809 
CC @sssaito - I have done some basic unit-testing, but no science verification. Please report in #809 what you find after you start doing science with this function, and close the issue if all looks good.

Add new `mock_observables.pair_counters.weighted_npairs_s_mu` function

---

halotools/sim_manager/cached_halo_catalog.py
halotools/sim_manager/halo_table_cache.py
halotools/sim_manager/halo_table_cache_log_entry.py
halotools/sim_manager/ptcl_table_cache.py
halotools/sim_manager/ptcl_table_cache_log_entry.py
halotools/sim_manager/rockstar_hlist_reader.py
halotools/sim_manager/tabular_ascii_reader.py
halotools/sim_manager/tests/test_cached_halo_catalog.py
halotools/sim_manager/tests/test_load_default_halocat.py
halotools/sim_manager/user_supplied_halo_catalog.py
halotools/sim_manager/user_supplied_ptcl_catalog.py
halotools/utils/python_string_comparisons.py

This PR attempts to resolve user-reported errors related to python 3.6 compatibility: #821, #826. 
@johannesulf - would you mind testing whether your error is resolved by this PR before I merge? Fixing bugs related to python 3.6 is the last significant Issue to resolve before releasing v0.6, and I'm hoping this will do the trick.

Python 3.6 bug fixes

---

docs/function_usage/utility_functions.rst

Addresses the first line item of #802.

Add top-level documentation for utils sub-package

---

CHANGES.rst
halotools/empirical_models/assembias_models/heaviside_assembias.py
halotools/empirical_models/model_helpers.py
halotools/empirical_models/occupation_models/tinker13_components.py
halotools/empirical_models/tests/test_model_helpers.py

Removed bounds_enforcing_decorator_factory

---

halotools/utils/inverse_transformation_sampling.py
halotools/utils/tests/test_its.py

docstring improvements to build_cdf_lookup function

---

CHANGES.rst
halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/tests/test_hod_mock_factory.py

Simple bug fix resolving #801.

Bug fix for estimate_ngals method

---

halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/kernels/mc_generate_nfw_radial_positions.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/kernels/tests/test_mc_generate_nfw_radial_positions.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/sfr_biased_nfw_phase_space.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_biased_nfw/test_conc_gal_bias_behavior.py
halotools/mock_observables/pair_counters/npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/npairs_jackknife_xy_z.py
halotools/mock_observables/pair_counters/pairs.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_pairwise_distance_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_weighted_npairs_s_mu.py
halotools/mock_observables/pair_counters/test_pair_counters/test_wnpairs_pure_python.py
halotools/tests/test_amurrica.py
halotools/utils/tests/data/dummy_ascii.dat
halotools/utils/tests/setup_package.py
halotools/utils/tests/test_io_utils.py
halotools/utils/tests/test_python_string_comparisons.py

Added many new unit-tests after reviewing test coverage outputs

Unit testing improvements

---

halotools/__init__.py
halotools/empirical_models/composite_models/tests/test_preloaded_models.py
halotools/empirical_models/occupation_models/tests/test_cacciato09_clf.py
halotools/empirical_models/occupation_models/tests/test_leauthaud11_hod.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_nfw_phase_space/test_nfw_phase_space.py
halotools/mock_observables/group_identification/test_groups/test_fof_groups.py
halotools/mock_observables/isolation_functions/tests/test_conditional_cylindrical_isolation.py
halotools/mock_observables/pair_counters/test_pair_counters/test_marked_npairs_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_pairwise_distance_3d.py
halotools/mock_observables/pairwise_velocities/tests/test_mean_radial_velocity_vs_r.py
halotools/mock_observables/tests/test_occupation_stats.py
halotools/sim_manager/tests/test_fake_sim.py
halotools/utils/tests/test_array_indexing_manipulations.py
halotools/utils/tests/test_crossmatch.py

@aphearin - I had a look at bf16872 that you added in response to #803. I think I misled you a bit due to my misunderstanding of what goes into the `test()` function's `kwargs` vs `args`.  I *think* this version does the job, though?  Can you give this a try and see if it's what you were thinking? (it's the same as yours except for the last commit changing the `test_installation` function)
If merged, I think this closes #803

Add test_installation function 

---

docs/quickstart_and_tutorials/index.rst
docs/quickstart_and_tutorials/tutorials/merger_tree_analysis_example.rst
halotools/utils/group_member_generator.py

This PR addresses a couple of line items in #802 by adding a tutorial for the use-case presented by @msbovill and embedding links to all relevant tutorials within the docstring of `group_member_generator`

Tutorial on merger tree analysis

---

docs/install.rst
docs/quickstart_and_tutorials/getting_started_overview.rst

Added documentation for newly added test_installation feature, resolving #841

Improved installation docs

---

CHANGES.rst

Added PR number associated with new function rp_pi_tpcf_jackknife

updated changelog

---

CHANGES.rst
halotools/mock_observables/radial_profiles/radial_profile_3d.py
halotools/mock_observables/radial_profiles/tests/test_radial_profile_3d.py

Bugfix for parallel implementation of radial_profile_3d

---

.travis.yml

Resolves #848. Special thanks to @bsipocz.

Restored testing in 3.5 environments

---

CHANGES.rst
halotools/mock_observables/radial_profiles/radial_profile_3d.py
halotools/mock_observables/radial_profiles/tests/test_radial_profile_3d.py

Bugfix for non-PBC behavior of radial_profile_3d function

---

halotools/mock_observables/counts_in_cells/counts_in_cylinders.py
halotools/mock_observables/counts_in_cells/tests/test_counts_in_cylinders.py

Cleaned up confusing syntax for counts-in-cylinders calculation

syntax cleanup

---

README.md
docs/whats_new.rst
docs/whats_new_history/whats_new_0.6.rst

README now shows that v0.6 is the latest release

Updated readme

---

CHANGES.rst
README.md
docs/function_usage/utility_functions.rst
docs/index.rst
docs/whats_new.rst
docs/whats_new_history/whats_new_0.6.rst
docs/whats_new_history/whats_new_0.7.rst
docs/whats_new_history/whats_new_v0x_history.rst
halotools/utils/__init__.py
halotools/utils/matrix_operations_3d.py

The new module implements 3d rotations, dot products, etc.

Added new `utils` module for 3d matrix operations

---

halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/nfw_phase_space.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_nfw_phase_space/test_nfw_phase_space_monte_carlo.py
halotools/utils/matrix_operations_3d.py

Resolved bounds checking bug in mc_generate_nfw_phase_space_points argument handling raised in Issue #870

Monte Carlo NFW bugfix

---

docs/quickstart_and_tutorials/tutorials/model_building/cam_tutorial_pages/cam_tutorial.rst

Fixed import statement in quick demo of new CAM algorithm

Minor docs cleanup

---

halotools/empirical_models/abunmatch/engines/bin_free_cam_kernel.pyx

Minor cleanup to cython engine of bin-free CAM

Cleaned up cython engine

---

halotools/mock_observables/counts_in_cells/counts_in_cylinders.py
halotools/mock_observables/counts_in_cells/tests/test_counts_in_cylinders.py

Thanks to @Christopher-Bradshaw for the bug report #908 and fix

Implemented bugfix to resolve #908, as well as regression test.

---

halotools/mock_observables/counts_in_cells/counts_in_cylinders.py

#909 fixed the code, this fixes the (unrelated) docs thing I mentioned in #908.

Correct docs for counts_in_cylinders (see #908)

---

CHANGES.rst
halotools/utils/load_umachine_binaries.py

New code loads UniverseMachine SFR catalog binary outputs into a python interpreter

Added load_um_binary_sfr_catalog function

---

CHANGES.rst
docs/quickstart_and_tutorials/development/contributors.rst

Chris Bradshaw now included as a contributor now that #913 is merged.

Modified changelog and package contributor list 

---

halotools/_astropy_init.py

This is an automated update made by the astropy package-template ``batchpr``
tool :robot: - feel free to close if it doesn't look good!
You can report issues to @bsipocz.

Package-template update: _astropy_init.py

---

halotools/empirical_models/occupation_models/zheng07_components.py

This pull request resolves issue #936

Make zheng07_components compatible with Assembias models

---

halotools/empirical_models/factories/prebuilt_model_factory.py
halotools/sim_manager/fake_sim.py

I was learning how halotools does these models and noticed some trivial issues

Update some docstrings + error messages

---

halotools/mock_observables/counts_in_cells/counts_in_cylinders.py
halotools/mock_observables/counts_in_cells/tests/pure_python_counts_in_cells.py
halotools/mock_observables/counts_in_cells/tests/test_counts_in_cylinders.py

I don't think there is a way to do an autocorrelation in the `counts_in_cylinders` at the moment. It would be useful for some work I am doing and is a pretty small change.
Let me know if there is anything you want done differently.
Edit: I don't think test failures are this change.

Provide a way to do an autocorrelation in `counts_in_cylinders`

---

halotools/sim_manager/cached_halo_catalog.py
halotools/sim_manager/download_manager.py
halotools/sim_manager/halo_table_cache.py
halotools/sim_manager/halo_table_cache_log_entry.py
halotools/sim_manager/ptcl_table_cache.py
halotools/sim_manager/ptcl_table_cache_log_entry.py
halotools/sim_manager/rockstar_hlist_reader.py
halotools/sim_manager/tests/test_cached_halo_catalog.py
halotools/sim_manager/tests/test_halo_table_cache.py
halotools/sim_manager/tests/test_halo_table_cache_log_entry.py
halotools/sim_manager/tests/test_ptcl_table_cache.py
halotools/sim_manager/tests/test_ptcl_table_cache_log_entry.py
halotools/sim_manager/user_supplied_halo_catalog.py
halotools/sim_manager/user_supplied_ptcl_catalog.py

Resolved all warnings due to h5py.File function changing default behavior

Resolved h5py warnings

---

.travis.yml
appveyor.yml

WIP PR to get travis tests working again

Remove testing on Travis for python < 3.7

---

halotools/sim_manager/tests/test_user_supplied_halo_catalog.py
halotools/sim_manager/user_supplied_halo_catalog.py

Resolves #936 
CC @rainwoodman

Include support for empty user-supplied halo catalogs. 

---

halotools/empirical_models/abunmatch/noisy_percentile.py
halotools/empirical_models/abunmatch/tests/test_noisy_percentile.py

Resolves #939. 
cc @mclaughlin6464

Fixed bug in treatment of noisy_percentile=-1 edge case. 

---

halotools/empirical_models/composite_models/hod_models/tests/test_zheng07.py
halotools/empirical_models/smhm_models/tests/test_zu_mandelbaum15.py
halotools/mock_observables/mock_observables_helpers.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_xy_z.py
halotools/mock_observables/pairwise_velocities/tests/test_pairwise_velocity_helpers.py
halotools/mock_observables/surface_density/tests/test_mass_in_cylinders.py
halotools/mock_observables/two_point_clustering/clustering_helpers.py
halotools/mock_observables/two_point_clustering/rp_pi_tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/tests/test_angular_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/tests/test_wp_jackknife.py
halotools/mock_observables/two_point_clustering/tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/wp_jackknife.py
setup.cfg

Very minor changes to testing suite eliminates a hundred warnings or so.

Reduce testing warnings

---

halotools/mock_observables/two_point_clustering/rp_pi_tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/wp_jackknife.py

This resolves some future warnings.

Changed all uses of np.matrix --> np.array 

---

halotools/sim_manager/tabular_ascii_reader.py
halotools/sim_manager/tests/test_tabular_ascii_reader.py

This PR resolves #956. Thanks to @saitosmst for identifying the fix.

Implemented python 3 fix to TabuarAsciiReader 

---

docs/install.rst
docs/installing_halotools_with_virtualenv.rst

The suggested environment in the docs is now python 3.7. Resolves #951.

Updated installation instructions

---

halotools/empirical_models/occupation_models/tinker13_components.py
scripts/convert_documentation_tutorials.py

This pull request addresses #989

fixed python 2 specific code

---

.github/workflows/ci_tests.yml

Added basic yml to implement GitHub Actions to address #1000.

Added ci_tests.yml

---

.github/workflows/ci_tests.yml
halotools/utils/tests/test_its.py
tox.ini

Trivial change to check that CI is running properly using tox with GitHub workflows

Reformatting to testing module by black

---

halotools/empirical_models/occupation_models/tests/test_zu_mandelbaum15_components.py
halotools/empirical_models/occupation_models/zu_mandelbaum15_components.py
halotools/empirical_models/smhm_models/zu_mandelbaum15.py

Fixed bug in the central occupation function of the Zu & Mandelbaum 2016 HOD. Was previously using natural exponentiation instead of base-10. It would be great if @AlanPearl could confirm that his SV tests pointed to this same specific fix before this gets merged into master.

Zu hod bugfix

---

halotools/empirical_models/component_model_templates/binary_galprop_models.py
halotools/empirical_models/component_model_templates/prim_galprop_model.py
halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/model_factory_template.py
halotools/empirical_models/occupation_models/occupation_model_template.py
halotools/empirical_models/phase_space_models/analytic_models/halo_boundary_functions.py
halotools/empirical_models/phase_space_models/analytic_models/profile_model_template.py
halotools/empirical_models/phase_space_models/analytic_models/tests/test_halo_boundary_functions.py
halotools/mock_observables/void_statistics/underdensity_prob_func.py
halotools/mock_observables/void_statistics/void_prob_func.py
halotools/sim_manager/download_manager.py
halotools/sim_manager/supported_sims.py
halotools/sim_manager/tabular_ascii_reader.py
halotools/utils/io_utils.py
halotools/utils/tests/test_value_added_halo_table_functions.py

Resolves FutureDeprecation warning in astropy

Change obsolete call to astropy.core.cosmology to astropy.cosmology

---

halotools/utils/tests/test_value_added_halo_table_functions.py
halotools/utils/value_added_halo_table_functions.py

Add new calculator for uber_hostid quantity

Uber hostid

---

CHANGES.rst
docs/install.rst
docs/installing_halotools_with_virtualenv.rst
docs/quickstart_and_tutorials/development/contributors.rst
docs/whats_new_history/whats_new_v0.8.rst
docs/whats_new_history/whats_new_v0x_history.rst
setup.py

This PR updates the documentation for the soon-to-be-released v0.8

update docs for v0.8

---

.github/workflows/wheels.yml
halotools/conftest.py
halotools/utils/autosummary_workaround.py

Use pytest_astropy_header.display

---

.github/workflows/ci_tests.yml
halotools/conftest.py
halotools/empirical_models/factories/prebuilt_model_factory.py
halotools/empirical_models/occupation_models/occupation_model_template.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_biased_nfw/test_conc_gal_bias_behavior.py
halotools/mock_observables/pair_counters/pairs.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_s_mu.py
halotools/mock_observables/two_point_clustering/tpcf_one_two_halo_decomp.py
halotools/sim_manager/tests/test_cached_halo_catalog.py
halotools/sim_manager/tests/test_download_manager.py
halotools/sim_manager/tests/test_user_supplied_halo_catalog.py
halotools/utils/crossmatch.py
setup.py

Halotools seems to be incompatible with recent versions of Astropy. CI only passes when `install_requires` has `astropy>=1`.

Change install_requires to astropy v5

---

halotools/conftest.py
halotools/empirical_models/composite_models/hod_models/tests/test_tinker13.py
halotools/empirical_models/composite_models/hod_models/tinker13.py
halotools/empirical_models/factories/tests/test_hod_factory.py
halotools/empirical_models/factories/tests/test_hod_mock_factory.py
halotools/empirical_models/occupation_models/tests/test_zheng07_satellites.py
halotools/empirical_models/smhm_models/tests/test_moster13.py
halotools/empirical_models/smhm_models/tests/test_redshift_defensiveness.py
halotools/mock_observables/counts_in_cells/tests/test_counts_in_cylinders.py
halotools/mock_observables/radial_profiles/tests/test_radial_profile_3d.py
halotools/mock_observables/tests/test_mock_observables_helpers.py
halotools/mock_observables/two_point_clustering/tests/test_clustering_helpers.py
halotools/mock_observables/two_point_clustering/tests/test_rp_pi_tpcf_jackknife.py
halotools/sim_manager/download_manager.py
halotools/sim_manager/tests/test_download_manager.py
halotools/tests/docs_code_block_tests/test_preloaded_mockpop.py

This PR attempts to resolve all warnings raised during unit testing.

Resolve warnings in unit testing

---

README.rst
halotools/empirical_models/occupation_models/tests/test_zheng07_satellites.py
tox.ini

Trivial change to README pointing out Argonne update to to license

Update license description

---

README.rst

Trivial PR to merge and get access

Trivial newline added to README

---

.github/workflows/wheels.yml
CHANGES.rst

Update docs for the 0.8.2 release

Update changelog and whats new for v0.8.2

---

.github/workflows/wheels.yml
CHANGES.rst
halotools/empirical_models/factories/tests/test_hod_mock_factory.py
halotools/sim_manager/tests/test_cached_halo_catalog.py
halotools/sim_manager/tests/test_download_manager.py
halotools/sim_manager/tests/test_supported_sims.py

Restore wheels.yml to build on release only

Restore wheels.yml to build on release only

---

.github/workflows/wheels.yml

Build wheels only for published releases instead of every PR

Build wheels only for published releases instead of every PR

---

.github/workflows/wheels.yml
CHANGES.rst
README.rst

Test wheels build and prepare for release of `v0.9.0`

Test wheels

---

CHANGES.rst
docs/whats_new.rst

Update whats new section

---

.github/workflows/ci_tests.yml
.github/workflows/cron_tests.yml
.github/workflows/wheels.yml
.readthedocs.yml
setup.cfg
tox.ini

Drop support for python 3.9

---

.eggs/README.txt

Remove .eggs

---

.github/workflows/wheels.yaml

Build wheel for OSX ARM64

---

.github/workflows/wheels.yaml
CHANGES.rst

Update `CHANGES.rst` with new entry for minor release `v0.9.2` that brings in compatibility with Astropy 7.

Changelog update

---

halotools/_astropy_init.py

Remove import of TestRunner from astropy.tests.runner

---

halotools/mock_observables/mock_survey.py

Extend redshift of `ra_dec_z` function from z=1 to z=20

Extend redshift of `ra_dec_z` function from z=1 to z=20
