astropy/halotools

.travis.yml

This closes #21 by just not running the numpy builds for versions < 1.9. Hopefully the travis tests will start passing once this is in.
This is probably best considered a work-around, because there are some subtle bugs that can creep in if you don't test older versions of numpy.  Unless of course you don't mind just requiring numpy 1.9 (or at least saying "untested/not guaranteed for older versions) - then there's no need to test them at all.
cc @aphearin

comment-out the travis builds checking numpy versions other than 1.9

---

halotools/empirical_models/model_factories.py

@andrew-zentner & @duncandc - The problem was as I suspected: rvir is in kpc, while halo centers are in mpc. This PR gives a quick fix to the problem. A more comprehensive fix is actively in the works.

Corrected bug in satellite position assignment

---

halotools/empirical_models/mock_factories.py

This is needed so that the populate() method can be called repeatedly within the same python session.

galaxy_table now is deleted upon HodMockFactory call to allocate_memory

---

docs/install.rst

Trivial change to docs. Code should not be built before calling the installer.

Changed install instructions

---

halotools/mock_observables/groups.py

added a kind of ugly work-around to deal with the issue that there are two packages called igraph.  I am not sure how we want to deal with this in the long run.
@aphearin do you want to see if this solves your problem?

work around for igraph package naming issue.

---

docs/rtd-pip-requirements

Hopefully this will fix the current RTD docs build problem.

Added h5py to rtd-pip-requirements

---

docs/rtd-pip-requirements
halotools/sim_manager/catalog_manager.py
halotools/sim_manager/supported_sims.py

For some reason, RTD was having problems building h5py, so I just hid h5py from the docs build as a workaround.

Removed h5py from module-wide imports and docs build

---

halotools/empirical_models/__init__.py
halotools/empirical_models/assembias.py
halotools/empirical_models/halo_prof_components.py
halotools/empirical_models/hod_designer.py
halotools/empirical_models/model_factories.py
halotools/empirical_models/model_helpers.py

Only change needed to get this finally integrated was to have halo profile models sub-class GalPropModels, and to remove the needless restriction that component models have a mc_galprop_key method. Now GalPropModels only bind the galprop_key, that's it.

Merged hod designer branch 

---

halotools/empirical_models/assembias.py
halotools/empirical_models/hod_components.py
halotools/empirical_models/hod_designer.py
halotools/empirical_models/model_factories.py

Minor adjustments to the behavior of the HodArchitect class. Measures are now taken to ensure that swapping out components with different thresholds raise an exception/warning, as appropriate. Also, the new_haloprop_func_dict mechanism is now automatically activated for all HeavisideAssembias components.

Abhod tweaks

---

docs/mock_observations/mock_observables_api.rst
docs/mock_observations/overview.rst
halotools/empirical_models/mock_factories.py
halotools/empirical_models/mock_helpers.py
halotools/empirical_models/model_defaults.py
halotools/empirical_models/model_factories.py
halotools/mock_observables/clustering.py
halotools/sim_manager/cache_config.py
halotools/sim_manager/supported_sims.py

Branch introduces several convenience functions for mock and model objects. There are now compute_galaxy_clustering and compute_galaxy_matter_cross_clustering methods bound to both mock and composite model objects. The latter generates a sequence of mocks, computes the signal in each one, and returns the median in each bin. Mock objects also now have a compute_groupids method. All of these functions are simple wrapper behaviors for the relevant mock_observables functions. This branch also introduces mock_observables documentation that builds, and a skeleton organization for documenting this sub-package.

Mockobs wrappers

---

halotools/empirical_models/preloaded_hod_blueprints.py

Deleted new_haloprop_func_dict from satellite model during creation of Hearin15 blueprint for cases where the central model already has the dict. Resolves #135

Hearin15 model no longer raises needless warning. 

---

halotools/empirical_models/model_factories.py

The problem was that HaloCatalog does not accept **kwargs, but **kwargs was being passed on from the compute_galaxy_clustering and compute_galaxy_matter_cross_clustering methods to HaloCatalog. As introduced in 78816235053ffcb5bb1ffb0130def27b890faa50 , HaloCatalog does not accept **kwargs to protect against the bug pointed out in #132 . So the solution was simply to create a new function keyword argument dictionary within the namespace of compute_galaxy_clustering and compute_galaxy_matter_cross_clustering.

Fixed bug in compute_clustering convenience function

---

halotools/empirical_models/mock_factories.py

PR resolves #164 
The source of the problem was really simple. When the monte carlo position assignment method `mc_pos` in the monte_carlo_phase_space module accepts a halo_table argument, this method assumes that the 'x', 'y', and 'z' keys have already been set to the halo-centric positions 'halo_x', 'halo_y', and 'halo_z'. However, the mock factory overhaul was not implementing this, and the 'x', 'y', and 'z'  columns were all just zero when this function was called within the populate_mock method.

fixed bug in satellite position assignment

---

halotools/empirical_models/mock_factories.py
halotools/empirical_models/model_factories.py

* Fixed satellite_fraction method to properly deal with multiple, independently-defined satellite populations. 
* Renamed model.compute_galaxy_clustering method to model.compute_average_galaxy_clustering, resolving #168 .

Mock convenience bug fixes

---

halotools/empirical_models/monte_carlo_phase_space.py

Now a warning message is only issued for lookup-build times that exceed 5 seconds.

Changed default warning message behavior of NFWPhaseSpace 

---

halotools/utils/array_utils.py
halotools/utils/tests/test_array_utils.py

Now have the option to specify a dtype for when using the convert_to_ndarray method. 
@duncandc - now there's no need for the .astype("float64") lines in mock_observables, in case you find this convenient.

added input dtype feature to convert_to_ndarray

---

halotools/empirical_models/factories/model_factory_template.py

Fixed minor bug that was causing the **compute_average_...* functions to misbehave when passed non-default simulations.

Simname bugfix

---

docs/function_usage/phase_space_models_functions.rst

Just removed some links that were the only visible difference between the phase space models and remaining sections on the docs subsection Function-usage examples by category. Will not know if this works until RTD builds the PR. At worst a lateral move.

Attempt to fix the RTD build problem

---

docs/autosummary_workaround.py
docs/conf.py
docs/full_ref_api/halotools_full_api.rst
docs/function_usage/empirical_model_factory_functions.rst
docs/function_usage/hod_occupation_functions.rst
docs/function_usage/phase_space_models_functions.rst
docs/index.rst

As recently discussed at length with @aphearin on slack, it turns out there's a bug in `sphinx`'s autosummary that was causing many of the associated problems with the docs.  This PR addresses that by adding a small sphinx extension that just fixes the bug 
The extension looks complex, but it's really just copied-and-pasted from sphinx, with the one change being on line 28: ``if not documenter.check_module()`` -> ``if documenter.options.members and not documenter.check_module()``. 
This also fixes up `phase_space_models_functions.rst` to be compatible with the extension - other docs that are supposed to have `autosummary` tables will need to be switched to follow this form (or similar).  
This also makes a few changes in the docs, most visible of which is the addition of a section for the …

Make autosummary tables work

---

.travis.yml
halotools/mock_observables/pair_counters/cpairs/setup_package.py
halotools/mock_observables/pair_counters/marked_cpairs/setup_package.py

This updates the ``.travis.yml`` file to hopefully get travis working again - ``anaconda`` recently made some changes that were causing the tests to not run correctly.
Moving forward, we'll probably want to do what astropy/package-template#140 is suggesting, but I'm not sure how to do that you, so probably best to get this in now, and then when astropy/package-template#140 is merged, pull that out and into halotools.

update travis builds for conda and travis changes

---

halotools/mock_observables/pair_counters/test_pair_counters/test_marked_double_tree_pairs.py
halotools/mock_observables/test_clustering/test_marked_tpcf.py
halotools/mock_observables/test_clustering/test_tpcf.py
halotools/mock_observables/test_clustering/test_tpcf_jackknife.py
halotools/mock_observables/test_clustering/test_tpcf_one_two_halo.py

Runtime on my machine improved from ~100s to ~60s with these changes. The remaining big slow-downs are test_pair_matrix and test_marked_tpcf, as neither of these permit cell_size manipulation. They're all marked as "slow", so the test suite can be run much faster by throwing the appropriate py.test flag.

Sped up many tests using approx_cell1_size = [rmax, rmax, rmax]

---

halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/model_factory_template.py

Minor updates to the convenience functions bound to the model factory instances. This fixes bugs related to the fact that the mock_observables sub-package no longer has a clustering sub-directory.

Convenience bugfix

---

.travis.yml

This implements a change to the tests that I discussed earlier today with @aphearin: it adds `h5py` as a dependency for the travis tests.  Testing `h5py` functionality is generally desired because basically the only reason h5py is not a required dependency is because it won't build on RTD.
This also adds an additional Travis build that's the same as the standard py2.7 build *except* that it does *not* have `h5py` this is here to make sure that an "accidental" dependency isn't injected (e.g., a module-level import of `h5py`), as in that case the RTD builds will start failing.

Make h5py a travis dependency

---

halotools/empirical_models/phase_space_models/nfw_phase_space.py
halotools/mock_observables/pair_counters/double_tree_pairs.py
halotools/mock_observables/pair_counters/double_tree_per_object_pairs.py

RTD currently fails due to a pytest import in two mock_observables source code modules. pytest was not used in the modules, so the imports were deleted.

Remove needless pytest imports from source code

---

README.md

Coverage shows as 71% even though it's 84% on my local machine. This difference is due to --remote-data differences, and many tests of sim_manager that are decorated with APH_MACHINE and HAS_H5PY.

Add coveralls badge to README

---

docs/install.rst

Now there is no optional dependencies section.

Update docs to reflect bs4 and requests being core dependencies

---

halotools/empirical_models/composite_models/tests/test_preloaded_models.py
halotools/empirical_models/factories/model_factory_template.py

Fix bug related to which simulation/snapshot is populated during calls to the compute_average_galaxy_matter_cross_clustering and compute_average_galaxy_clustering convenience functions. There is also a related bug fix in the populate_mock method. 
Resolves #303  and #304 .

Fix bug in populating mocks at high redshift

---

.travis.yml
docs/quickstart_and_tutorials/tutorials/user_supplied_halo_catalogs.rst
docs/quickstart_and_tutorials/tutorials/working_with_alternative_particle_data.rst
halotools/sim_manager/__init__.py
halotools/sim_manager/cached_halo_catalog.py
halotools/sim_manager/ptcl_table_cache.py
halotools/sim_manager/ptcl_table_cache_log_entry.py
halotools/sim_manager/tests/test_cached_halo_catalog.py
halotools/sim_manager/tests/test_user_supplied_halo_catalog.py
halotools/sim_manager/tests/test_user_supplied_ptcl_catalog.py
halotools/sim_manager/user_supplied_halo_catalog.py
halotools/sim_manager/user_supplied_ptcl_catalog.py

This PR introduces the UserSuppliedPtclCatalog class and associated functionality. Users can now obtain their own downsamplings of dark matter particles and use them with Halotools, optionally storing them in cache. This functionality is needed, for example, if users want to use different simulations besides the Halotools-provided ones, or even just different redshifts of the same simulations. This way, users can compute, for example, the galaxy-galaxy lensing signal with both halos and particles that they provide themselves.

Support User-Supplied Particle Catalogs

---

halotools/empirical_models/factories/hod_model_factory.py
halotools/empirical_models/factories/subhalo_model_factory.py
halotools/empirical_models/occupation_models/occupation_model_template.py

This PR fixes a bug in how a composite model determines its redshift from the collection of components, which is now more robust. Component models can now also specify list_of_haloprops_needed.

factory bugfixes

---

halotools/empirical_models/composite_models/hod_models/tests/test_tinker13.py
halotools/empirical_models/factories/model_factory_template.py
halotools/empirical_models/factories/prebuilt_model_factory.py
halotools/empirical_models/factories/tests/test_prebuilt_hod_model_factory.py
halotools/empirical_models/factories/tests/test_prebuilt_subhalo_model_factory.py
halotools/sim_manager/fake_sim.py

The populate_mock, compute_average_galaxy_clustering, and compute_average_galaxy_matter_cross_clustering methods now support a simname='fake' keyword argument, which is useful for unit-testing.

Fake mock population

---

.travis.yml
halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/model_factory_template.py
halotools/empirical_models/factories/subhalo_mock_factory.py

Previously, when populating mocks, the *entire* halo catalog was bound to the mock object. This memory usage was needless. Now only the rows passing the appropriate cuts are stored, and also only the columns required by the model. This should reduce the dominant source of memory usage of the mock factories factory by a few hundred percent. 
CC @mjvakili - this is a pre-requisite to implementing the sample variance feature we have been discussing, but it should immediately improve the memory leak issue you may have been encountering.

Mock factory memory improvements

---

.travis.yml

Turns out astropy/ci-helpers#61 fixed this problem so there's no need for the change from 93b1012747e3f4705c4bca3a7d2caf2fd6eaedd5 after all.  This PR un-does it so that it doesn't lead to possible confusion later on

remove now-uneeded 1.5.1 non-specification

---

halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/model_factory_template.py
halotools/empirical_models/factories/subhalo_mock_factory.py
halotools/empirical_models/factories/tests/test_hod_mock_factory.py
halotools/sim_manager/cached_halo_catalog.py

This PR introduces a new 'masking_function' keyword argument to the populate() method bound to HodMockFactory objects. The masking function can be used to select a specific sub-population of halos in the halo catalog *prior* to calling any of the mock-generating functions. As discussed with @mjvakili and @changhoonhahn, this feature can be exploited to forward model sample variance during a Halotools likelihood analysis by populating randomly selected subvolumes of a simulation. 
This PR is only a baby step towards the full functionality that will be offered when #333 is resolved.

Masked population

---

docs/_static/halotools.css

This PR fixes the long-standing problem of long strings in the docs overflowing. Before:
After:
I'll issue a PR against the astropy-helpers on this so that it goes more widely, so it might be better to hold off on that if this gets merged in there quickly.  But if you want to do a release or just send around cleaner docs before then, then this can just be merged.

Fix overflowing text in sphinx sidebar

---

docs/_static/halotools.css

This PR just updates halotools' helpers to include the fix from astropy/astrop-helpers#217
This should do the same thing as #331, but using the updated helpers instead of customizing halotools' css.  So this closes #331 (i.e., #331 should not be merged assuming this works).

Update helpers to version with fix for overflowing documentation

---

setup.py

This changes the version to 0.1.dev .  Some parts of the setup function and doc builders assume the version is in-development only if it ends in "dev", so having a "a0" ending might confuse some of them.  At the very least it makes debbuging doc issues easier because it includes the git commit number...
It could also be 0.0.dev if the first release is supposed to be 0.0, though, @aphearin

Change version string to 0.1.dev

---

halotools/empirical_models/model_defaults.py

Change model_defaults.default_haloprop_list_inherited_by_mock to include 'halo_upid' so that subhalo-based mocks can identify centrals/satellites

Include 'halo_upid' as default inherited halo column

---

halotools/mock_observables/__init__.py
halotools/mock_observables/catalog_analysis_helpers.py
halotools/mock_observables/tests/test_catalog_analysis_helpers.py

This new mock_observables module has just one new function, mean_y_vs_x. 
This gives simple wrapper behavior around `scipy.stats.binned_statistic` and `np.histogram` so that with one line of code you can pass in a sample of *x* and *y* arrays and get <y>(x) in bins, and optionally an estimate of either the Poisson error-on-the-mean or just the variance.

Add catalog_analysis_helpers module 

---

halotools/utils/__init__.py
halotools/utils/aggregation.py
halotools/utils/tests/test_aggregation.py

This PR introduces a new `aggregation` module into `utils`. Currently, this module has just one function, `add_new_table_column`. This function will serve as the engine driving all group-wise calculations, e.g., computing host halo mass, host halo richness, subhalo mass gaps, <Rmem>, and broadcasting the newly computed quantity to the halo members.
Since `add_new_table_column` accepts an arbitrary callable python object as input, there is a high degree of flexibility for the group-wise calculations this function supports. This flexibility comes at the cost of speed: cython cannot compile an arbitrary unspecified python callable, so the loop over groups is done in pure python. All the same, the algorithm is quite fast as it is based entirely on existing, heavily optimized `Numpy.unique` …

Add aggregation module to perform group-wise calculations

---

halotools/sim_manager/cached_halo_catalog.py

Now, when any CachedHaloCatalog loads into memory, two halo properties are automatically added to the table (if not already present): 
1. halo_hostID (=-1 for hosts and =upid for subhalos)
2. halo_mvir_host_halo 
Uses the underlying group aggregation engine immediately after reading the table from disk. So halo tables now take another 1-2 seconds to initially load, but now they automatically have halo_hostid and halo_mvir_host_halo columns. Implementation is quite general, as it relies on the abstractly-written aggregation module, so this will naturally extend to requests for additional halo catalog properties as becoming "standard issue". This framework also resolves the problem of having multiple halo catalogs lying around on disk simply because one is a more useful "value-added" …

Pre-compute Mhost and hostID upon loading any CachedHaloCatalog

---

docs/rtd-pip-requirements

Despite #340 fixing *local* builds of the docs to no longer have the text overflow, the problem remains on readthedocs.  
Some testing with temporary branches leads me to strongly suspect that the problem is that ``docs/rtd-pip-requirements`` contains ``astropy-helpers``, so the *release* version of the helpers gets used on RTD rather than the version that's packaged with halotools.  This removes the helpers from ``rtd-pip-requirements``, hopefully resolving the overflow problem on RTD (what #340 was supposed to fix).

Fix overflow in RTD docs

---

halotools/empirical_models/factories/subhalo_mock_factory.py

Having upid and hostid together makes group analysis very easy, so it should be the default behavior to include this column if it is available. 
Together with #355, this PR resolves #287 .

Now adding halo_hostid to all subhalo mocks, if available

---

docs/quickstart_and_tutorials/mock_observations/mock_obs_pos_formatting.rst
halotools/mock_observables/angular_tpcf.py
halotools/mock_observables/delta_sigma.py
halotools/mock_observables/groups.py
halotools/mock_observables/isolation_criteria.py
halotools/mock_observables/marked_tpcf.py
halotools/mock_observables/mock_survey.py
halotools/mock_observables/nearest_neighbor.py
halotools/mock_observables/pairwise_velocity_stats.py
halotools/mock_observables/rp_pi_tpcf.py
halotools/mock_observables/s_mu_tpcf.py
halotools/mock_observables/tpcf.py
halotools/mock_observables/tpcf_jackknife.py
halotools/mock_observables/tpcf_one_two_halo_decomp.py
halotools/mock_observables/void_stats.py
halotools/mock_observables/wp.py

This PR adds a new docs tutorial page, plus adds links in the mock_observables function docstrings to this tutorial.

Add documentation for how to put x, y, z arrays into the mock_observables-accepted format

---

halotools/empirical_models/factories/subhalo_mock_factory.py

Add halo_mvir_host_halo as a default column in all subhalo-based mocks, if available

subhalo mocks automatically include host halo mass

---

halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/model_helpers.py
halotools/empirical_models/tests/test_model_helpers.py

Accomplished by adding velocity-flip feature to enforce_periodicity_of_box function in model_helpers

Enforce PBCs for velocities of satellites that scatter out of the box

---

halotools/sim_manager/tests/test_cached_halo_catalog.py
halotools/sim_manager/tests/test_download_manager.py
halotools/sim_manager/tests/test_halo_table_cache.py
halotools/sim_manager/tests/test_ptcl_table_cache.py
halotools/sim_manager/tests/test_rockstar_hlist_reader.py
halotools/sim_manager/tests/test_tabular_ascii_reader.py
halotools/sim_manager/tests/test_user_supplied_halo_catalog.py
halotools/sim_manager/tests/test_user_supplied_ptcl_catalog.py
halotools/utils/tests/test_array_utils.py

This PR makes another attempt to bring Windows-compatibility to Halotools. 
PR #386 resolved the inability to *install* the code, but as pointed out by @a-kravtsov, #386 still left behind many test suite failures. It appears that at least most of these actually indicate problems with the way the test suite was written, not Halotools source code. Summary of changes follows. 
1. Eliminated some needless hard-coding of the floating point type assertions in test_array_utils.py. 
2. Eliminated all appearances of `os.system('touch' + fname)` in the test suite for the `sim_manager` package. `touch` is a unix-specific system command, and so the test suite was raising exceptions due to its use. All temporary files are now created by writing an Astropy Table with a single entry. 
The above patches …

Windows test suite failure patches

---

halotools/sim_manager/download_manager.py

Bug pointed out by @a-kravtsov. When running `scripts/download_initial_halocat.py`, the DownloadManager does not detect the default halo catalog on the Yale server when being run from a windows machine. There is at least one reason why this behavior should be expected. The Yale server is unix, and so the correct paths to the halo catalogs should be names like "url/dirname/basename.hdf5". However, when the `_processed_halo_tables_available_for_download` of the `DownloadManager` builds the absolute paths using `BeautifulSoup`, the paths are generated using os.path.join(dirname, basename). When run from a windows machine, this will create a path with a name like "url\dirname\basename.hdf5", which will not match any path on the Yale server, and so the …

Resolve DownloadManager bug for windows users

---

halotools/sim_manager/halo_table_cache_log_entry.py
halotools/sim_manager/tests/test_halo_table_cache_log_entry.py

The `_verify_halo_ids_are_unique` method of the `halo_table_cache_log_entry` module had an unnecessary hard-coded test of integer typing that causes perfectly good halo catalogs to appear as if they are incorrectly typed on a windows platform. 
Bug pointed out by @a-kravtsov

Removed hard-coding of integer type checking during _safe_for_cache execution

---

halotools/sim_manager/halo_table_cache_log_entry.py

This PR attempts to resolve a remaining issue with windows compatibility, #385. The default halo catalog on windows machines fails the `_verify_halo_ids_are_unique` test in `safe_for_cache`, as pointed out by @a-kravtsov. This is most likely because the `halo_id` column stores long integers, and when these are type cast into a python `int`, some of the values get changed. The fix implemented here is to compare the `dtype.str` and ensure that it's an `i` or `u` data type.

Slight modification to halo_id integer dtype testing

---

halotools/mock_observables/pairwise_velocity_stats.py

This PR fixes a bug in the pairwise_velocity_stats module. There was a typo in the marked_pair_counts function that accidentally tried to pass `rbins` rather than `rp_bins`. The current PR resolves the bug and introduces a regression doctest that would have caught the error.

Add doctest to catch rp_bins --> rbins bug

---

halotools/utils/table_utils.py

Numpy's old convention for passing in an empty array for the bins in np.digitize(array, bins) was to return np.zeros(len(array)). The new convention is to raise an exception. This PR fixes the only Halotools call to np.digitize that was susceptible to this change in corner-case behavior.

Fixed corner case of np.digitize to accommodate the new numpy convention

---

halotools/empirical_models/assembias_models/heaviside_assembias.py
halotools/empirical_models/model_helpers.py
halotools/empirical_models/phase_space_models/monte_carlo_helpers.py
halotools/empirical_models/phase_space_models/tests/test_phase_space.py

This is the appropriate convention for simple linear interpolation through the abscissa, which is the most common usage of this wrapper. Suggestion due to @yyao.

Changed default convention of custom_spline. Now default is k=1.

---

halotools/empirical_models/factories/tests/test_hod_mock_factory.py
halotools/mock_observables/__init__.py
halotools/mock_observables/distances.py

This PR adds a new non-trivial test of the correctness of satellite positions during mock population. In particular, it is now manually checked that populating a full-scale mock with 'zheng07' into the default simulation results in satellite positions that lie within rvir of their host halo. Previously, this test was only performed at the unit-testing level. This new test is an integration test.

Satellite position testing

---

halotools/sim_manager/halo_table_cache_log_entry.py
halotools/sim_manager/tests/test_halo_table_cache_log_entry.py

This is a crude way to ensure that halo rvir has not accidentally but put in kpc/h units, which can lead to bugs in satellite position assignment of HOD-style models, as pointed out in #336 .

Now requiring halo_rvir > 50 to be safe_for_cache

---

halotools/empirical_models/factories/hod_model_factory.py
halotools/empirical_models/factories/subhalo_model_factory.py
halotools/empirical_models/factories/tests/test_hod_model_factory.py
halotools/empirical_models/factories/tests/test_subhalo_model_factory.py

An attempt to call either of the model factories with no arguments as if there were a default choice now raises an exception. 
This PR resolves #207

Improved error handling of subhalo and hod model factories

---

halotools/sim_manager/tests/test_tabular_ascii_reader.py

Previously, the testing suite for TabularAsciiReader had many decorations to run exclusively on APH_MACHINE. This has been dispensed with.

TabularAsciiReader test suite now runs on all machines

---

halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/model_factory_template.py
halotools/empirical_models/factories/tests/test_hod_model_factory.py
halotools/sim_manager/fake_sim.py

As pointed out by @nickhand, there were several awkward aspects of how the halo completeness cuts were applied during HOD mock generation. This PR addresses this by allowing the user to declare two arguments that may be passed either to the `HodMockFactory` constructor, or equivalently to the `populate_mock` function:
1. Num_ptcl_requirement 
2. halo_mass_column_key
These two arguments together permit the user to make more customizable initial halo completeness cuts with a simpler and more transparent interface. 
This PR also prompted a much-needed syntax cleanup for the `populate_mock` method, which had become very cluttered with nested control flow. 
@nickhand - since you discovered this awkwardness and will be using this feature in short order, would you mind providing some feedback on …

Simplify API for users declaring their own halo mass completeness cut

---

halotools/mock_observables/nearest_neighbor.py
halotools/mock_observables/pair_counters/double_tree_pairs.py
halotools/mock_observables/pair_counters/double_tree_per_object_pairs.py
halotools/mock_observables/pair_counters/marked_cpairs/pairwise_velocity_funcs.pyx
halotools/mock_observables/pair_counters/marked_double_tree_pairs.py
halotools/mock_observables/pairwise_velocity_stats.py
halotools/mock_observables/test_clustering/test_marked_tpcf.py
halotools/mock_observables/tests/cf_helpers.py
halotools/mock_observables/tests/test_distances.py
halotools/mock_observables/tests/test_nearest_neighbor.py
halotools/mock_observables/tests/test_pairwise_velocity_stats.py
halotools/mock_observables/tests/test_void_stats.py
halotools/mock_observables/void_stats.py
halotools/mock_observables/void_stats_helpers.py

Many new unit-tests added and associated bug-fixes. The functions that are changed are:
1. nearest_neighbors
2. pairwise velocity statistics
3. void statistics
In almost all cases, the bug fixes just addressed edge cases that previously raised uninformative error messages, e.g., if there was no nearest neighbor within a given search radius, the code used to raise a mysterious error message, now it no longer raises an exception. 
The only exception is with the pairwise velocity statistics. In this function, the periodic boundary conditions were not being handled correctly. The source of the bug has to do with the fact that the signs of the velocity was being flipped in an inconsistent way with the fact that the points were being pre-shifted by the pair-counting engine; this bug has been …

Improved testing of mock_observables sub-package

---

setup.py

Previously, a mysterious error message was issued if 3.x users attempted `python setup.py install`. Now the python version is checked immediately and an exception is raised if sys.version_info[0] >2

Now raising informative error message if a python 3.x user tries to install the code

---

halotools/empirical_models/factories/model_factory_template.py

There is now an explicit explanation that the convenience functions are not to be called during performance-critical applications such as MCMCs. Links the appropriate tutorials are provided for users who need to compute galaxy clustering and galaxy-matter cross-clustering when high-performance is vital. 
Documentation suggested by @andrew-zentner .

Improved docstring of compute_average_galaxy_clustering

---

halotools/empirical_models/factories/hod_model_factory.py

This was accidental due to an unintentionally reversed order set(list(_gal_type_list)) rather than the list(set(_gal_type_list)). There were no consequences to this error, but this could have led to buggy behavior in future attempts to access, for example, self.gal_types[index].

HodModelFactory gal_types is now a list, not a set

---

halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/subhalo_mock_factory.py
halotools/empirical_models/factories/tests/test_hod_model_factory.py
halotools/empirical_models/factories/tests/test_subhalo_model_factory.py

Now catching exceptions for attempts to populate a simulation that does not have a required halo property. Also, attempts to use and HOD-style model to populate a halo catalog without the `halo_upid` column are now also caught. 
This PR resolves #312 and #362.

Improve error handling of mock population

---

halotools/mock_observables/pair_counters/double_tree_pairs.py
halotools/mock_observables/pair_counters/marked_double_tree_pairs.py
halotools/mock_observables/pair_counters/test_pair_counters/test_double_tree_pairs.py

This PR adds new, highly non-trivial tests of `double_tree_pairs.npairs`. 
The documentation of the `npairs` now also reflects that if sample1 == sample2, the `npairs` function double-counts pairs. Thanks to @a-kravtsov for pointing out this potential source of confusion. 
This PR resolves #257.

Improved testing of npairs

---

halotools/utils/tests/test_array_utils.py

As pointed out by @andrew-zentner , test_convert_to_ndarray15 fails for out-of-date versions of astropy, and it is an utterly irrelevant test.

Removed needless unit test of convert_to_ndarray

---

halotools/mock_observables/clustering_helpers.py
halotools/mock_observables/test_clustering/test_tpcf.py
halotools/mock_observables/tpcf.py

This PR introduces an additional feature to the tpcf function: you can now optionally pass in a set of pre-computed random pairs. This feature is useful for MCMC applications populating multiple simulation volumes, as is currently being done by @mjvakili and @changhoonhahn.

Add precompute_RR feature into tpcf

---

halotools/sim_manager/tests/test_user_supplied_halo_catalog.py
halotools/sim_manager/tests/test_user_supplied_ptcl_catalog.py
halotools/sim_manager/user_supplied_halo_catalog.py
halotools/sim_manager/user_supplied_ptcl_catalog.py

Previously, there was a hard-coded check that an input redshift argument to a halo catalog had to be a float. This PR relaxes this requirement via duck-typing: if the `redshift` keyword argument can be converted to a float via the python built-in, the argument is permissible.

integer arguments for redshift are supported

---

halotools/mock_observables/large_scale_density.py
halotools/mock_observables/large_scale_density_helpers.py
halotools/mock_observables/tests/test_large_scale_density.py
halotools/mock_observables/tests/test_void_stats.py
halotools/mock_observables/void_stats.py

This PR addresses #236. There are two new functions introduced here: `large_scale_density_spherical_volume` and `large_scale_density_spherical_annulus`, both of which use `per_object_npairs`. 
Large-scale density estimations based on cylinders will have to wait for an implementation of `per_object_xy_z_npairs` in the `v0.2` release. 
CC @duncandc

Large scale density

---

ah_bootstrap.py
setup.py

This updates the bundeled astropy helpers to the latest helpers version, and also copies over the `ah_boostrap.py` from that to the root of halotools.
This should get rid of the deprecation warning from setuptools as well as anything else that might have been fixed in `ah_bootstrap` in the meantime.

Update helpers and bootstrap

---

.gitignore
MANIFEST.in

this update the halotools MANIFEST.in to actually include all the files that halotools is supposed to have.
@aphearin - if you don't know about ``MANIFEST.in``, it's a file that basically tells release commands like ``sdist`` what to put in the tarball.  Confusingly, though, any source files that are included in the setup script are *automatically* included.  But that misses things like .h files, .c files that aren't explicitly compiled as python modules, etc.  So this update should account for that (as well as being *less* heavy handed in what gets included in astropy_helpers - see the second commit).
While I said earlier to @aphearin that maybe this shouldn't get merged, I now think it should be prior to release regardless.  But there's possibly a separate problem that perhaps should be …

MANIFEST.in update

---

MANIFEST.in

There was a mistake in #443 - I added the ``MANIFEST.in`` line to include all the Cython source files but neglected to specify *where* (it should have been the halotools source dir, and in what's in master I think it instead looks for ``*.pxd *.c *.cpp *.h`` in any directory named ``*.pyx``.  But of course that's nothing.)

fix manifest to include source files *in the halotools* dir

---

halotools/mock_observables/pair_counters/cpairs/cpairs.pyx
halotools/mock_observables/pair_counters/cpairs/per_object_cpairs.pyx
halotools/mock_observables/pair_counters/cpairs/setup_package.py
halotools/mock_observables/pair_counters/double_tree_pair_matrix.py
halotools/mock_observables/pair_counters/double_tree_pairs.py
halotools/mock_observables/pair_counters/marked_cpairs/marked_cpairs.pyx
halotools/mock_observables/pair_counters/marked_cpairs/setup_package.py
halotools/mock_observables/pair_counters/marked_double_tree_pairs.py
halotools/mock_observables/pair_counters/test_pair_counters/test_marked_double_tree_pairs.py

Modest enhancements to performance of the mock_observables sub-package. Special thanks to @rainwoodman. 
@duncandc - have a look at https://github.com/aphearin/halotools/commit/3d2164275c5dc5d456a984019d08b95ad2bcb57d. This is a very minor change to how pool.map is used that is worth being aware of. Doing things the old way, there is communication between processes for every element of xrange(Ncell1). Doing things this new way, there is only one communication per chunk. It's a very minor change, but performance scales much better with the number of cores. Nothing for you to do, just pointing this out since you might be using this pattern again in the future. 
Note to @rainwoodman - this PR does not include your own Pool. I'd like to experiment with that more before merging.

Performance enhancements of mock_observables

---

halotools/mock_observables/pair_counters/cpairs/setup_package.py
halotools/mock_observables/pair_counters/marked_cpairs/setup_package.py

As suggested by @manodeep, `mock_observables` is now being compiled while throwing the `-march=native` flag, resulting in a 10% speedup of `npairs`.

Added new compiler flag to cython

---

halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/tests/test_hod_mock_factory.py

This PR addresses #473. For reference, below appears the example error message raised by the newly-added testing function `test_zero_halo_edge_case` dedicated to guaranteeing that a maximal cut will never be made in the future. This testing function attempts to populate the FakeSim with a cut that exceeds the maximum value of virial mass. 
@mclaughlin6464 - this is the best I can do to write an informative error message without understanding better what happened; if you encountered this problem, others are likely to as well, so your feedback would be appreciated. 
> HalotoolsError: During the pre-processing phase of HOD mock-making 
> controlled by the `preprocess_halo_catalog` method of the HodMockFactory,
> a cut on halo completeness is made. The column used in this cut
> is determined …

Masscut fix

---

halotools/sim_manager/tabular_ascii_reader.py

In the conversion to make this python 3 compliant by @bsipocz in 82cd264f916a80a3a592b39363f7bb4dae2ff5a3 a bug was introduced.
3.0 // 2.0 = 1.0 (type float)
The range() function does not like receiving floats.  I don't know if this bug shows up elsewhere, but @aphearin you should be aware.

fixed bug in ascii reader

---

halotools/mock_observables/tpcf_jackknife.py

This PR fixes an error in the docstring of the `tpcf_jackknife` function pointed out by @mclaughlin6464 in #497.

Correction to tpcf_jackknife docstring

---

halotools/mock_observables/clustering_helpers.py
halotools/mock_observables/delta_sigma.py
halotools/mock_observables/mock_observables_helpers.py
halotools/mock_observables/tests/test_clustering_helpers.py
halotools/mock_observables/tests/test_mock_observables_helpers.py
halotools/mock_observables/tpcf_estimators.py

This PR adds a few new helper functions to the `mock_observables` package to process function arguments and do bounds-checking with more transparency. Currently only implementing these improvements in the `delta_sigma` function, but the remaining `tpcf_xxx` functions will soon follow suit. This PR also fixes a couple of bugs in the docstring to `delta_sigma`.

Delta sigma control flow refactoring

---

docs/quickstart_and_tutorials/tutorials/catalog_analysis/galcat_analysis/basic_examples/crossmatching_galaxy_catalogs.rst
docs/quickstart_and_tutorials/tutorials/catalog_analysis/galcat_analysis/index.rst
docs/quickstart_and_tutorials/tutorials/catalog_analysis/halocat_analysis/crossmatching_halo_catalogs.rst
docs/quickstart_and_tutorials/tutorials/catalog_analysis/halocat_analysis/index.rst
docs/source_notes/empirical_models/factories/model_factory_composite_sequence_mechanisms.rst
halotools/utils/__init__.py
halotools/utils/crossmatch.py
halotools/utils/tests/test_crossmatch.py
halotools/utils/tests/test_value_added_halo_table_functions.py

This PR introduces a new user-facing function to the `utils` sub-package, `crossmatch`. This function returns the indices giving the correspondence between elements of an integer array `x` with values that have a match in an integer array `y`. When `x` and `y` have unique entries, this calculation is equivalent to the `join` function in `astropy.table`, but `crossmatch` also covers the case where the array `x` has repeated entries, and the arrays `x` and `y` may only be partially overlapping. This function is useful for transferring properties from one table to another, or also in doing specific kinds of group aggregation calculations in which some pre-computed property of the groups is broadcast to the members (the calculation of host halo mass is a common example). The `crossmatch` …

Crossmatch

---

halotools/sim_manager/tests/test_download_manager.py

The filenames for particle catalogs that are up on the Yale download location were incorrectly hard-coded in the test_download_manager.py module. This is now fixed.

Fixed bug in the testing module test_download_manager.py

---

halotools/mock_observables/group_identification/fof_groups.py
halotools/mock_observables/pair_counters/npairs_3d.py
halotools/mock_observables/pair_counters/npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/npairs_per_object_3d.py
halotools/mock_observables/pair_counters/npairs_projected.py
halotools/mock_observables/pair_counters/npairs_s_mu.py
halotools/mock_observables/pair_counters/npairs_xy_z.py
halotools/mock_observables/pair_counters/pairwise_distance_3d.py
halotools/mock_observables/pair_counters/pairwise_distance_xy_z.py

During the processing of the arguments passed to many of the functions in `mock_observables`, the initial positions are shifted in the case where there are no PBCs. Many of the functions failed to use the shifted positions and only used the original positions. The test suite did not cover this because there were no tests for which PBCs were turned off and positions did not span [0, Lbox]. This is now fixed.

Fixed bug in processing of arguments.

---

halotools/sim_manager/rockstar_hlist_reader.py
halotools/sim_manager/tabular_ascii_reader.py
halotools/sim_manager/tests/test_rockstar_hlist_reader.py

All relevant combinations of chunk lengths and number of ascii rows are now explicitly tested. 
It is now also possible to pass in chunk_memory_size to `RockstarHlistReader.read_halocat` - before this option was accidentally not passed on to the superclass. 
This PR resolves #478.

Added test of different chunk sizes to the RockstarHlistReader 

---

.gitignore
halotools/sim_manager/halo_table_cache_log_entry.py

This PR reduces the runtime it takes to load a CachedHaloTable into memory. Speedup introduced here is ~2x. The only change is to ensure that the table is only read into memory once when performing all the self-consistency checks associated with the `safe_for_cache` test. Further speedups to continue addressing #515.

Halo table read optimization

---

halotools/empirical_models/factories/hod_model_factory.py
halotools/empirical_models/factories/subhalo_model_factory.py
halotools/empirical_models/occupation_models/tinker13_components.py
halotools/utils/value_added_halo_table_functions.py

This PR addresses #141 by setting the docstrings of composite models to be equal to those defined in the component models.

Factory docstrings

---

halotools/empirical_models/occupation_models/tests/test_occupation_component.py
halotools/mock_observables/pair_counters/npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_3d.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf_one_two_halo.py
halotools/sim_manager/tests/test_rockstar_hlist_reader.py
halotools/utils/crossmatch.py
halotools/utils/tests/test_crossmatch.py

``np.random.random_integers`` is deprecated and raises warnings when using numpy v1.11, and thus causing failures for PR #531 and #532.

Removal of deprecated numpy function

---

.travis.yml
halotools/empirical_models/occupation_models/tests/test_occupation_component.py
halotools/mock_observables/pair_counters/npairs_jackknife_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_3d.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf_one_two_halo.py
halotools/sim_manager/tests/test_rockstar_hlist_reader.py
halotools/utils/crossmatch.py
halotools/utils/tests/test_crossmatch.py

Stable numpy is 1.11 at the moment. Adding np 1.10 build as well as the occasional prerelease build. 
Latter only runs if there is a prerelease available, otherwise sets the build to be successful.

Updating numpy version for travis

---

.travis.yml
appveyor.yml

Does what says on the tin. 
Python3 on windows currently fails with one test that needs more debugging, thus not including it in the appveyor file yet. 
Also adding the numpy prerelease build to the allowed failures as it halts in the middle of the build without any obvious reason.

Updating numpy and astropy versions for appveyor

---

halotools/empirical_models/factories/hod_model_factory.py
halotools/empirical_models/factories/model_factory_template.py
halotools/empirical_models/factories/subhalo_model_factory.py

Allow subhalo-based models to make a cut on halo catalog prior to initial mock population

---

docs/function_usage/index.rst
docs/quickstart_and_tutorials/index.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/zheng07_composite_model.rst
halotools/empirical_models/composite_models/smhm_models/behroozi10.py
halotools/empirical_models/factories/prebuilt_model_factory.py
halotools/empirical_models/occupation_models/leauthaud11_components.py
halotools/empirical_models/occupation_models/tinker13_components.py
halotools/empirical_models/occupation_models/zheng07_components.py
halotools/empirical_models/smhm_models/behroozi10.py

This PR addresses #543 by improving the documentation/tutorial of the Zheng+07 class. The default behavior remains the same, but the docs now explicitly state that you need to choose `modulate_with_cenocc` keyword to True if you are attempting to reproduce Zheng+07. 
There are other, smaller changes to the documentation that are part of this PR. Most of these changes are about improving the discoverability of the composite model tutorials, which should help make it easier for users to get pointed to the `modulate_with_cenocc` feature, and generally get pointed to sections of the docs that are relevant to doing science with a composite model.

Composite model docs

---

halotools/mock_observables/two_point_clustering/delta_sigma.py

This PR adds a caveat to the `delta_sigma` function. Although the Halotools implementation is a reasonable analysis choice, as discussed with @surhudm, as of this writing the current state of research into $\Delta\Sigma$ is actually insufficient to know the optimal, highest-precision way to predict this signal. So for the purposes of v0.2 release, there is simply a note made of this in the docstring. We'll revisit this following the release, changing #547 to have a v0.3 milestone.

Delta sigma docstring 

---

halotools/mock_observables/two_point_clustering/tests/locate_external_unit_testing_data.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_wp.py

This PR introduces a new kind test of the wp and tpcf functions. Binary files storing positions of points were provided to @manodeep, who used his `Corrfunc` code (https://github.com/manodeep/Corrfunc) to calculate `wp` and `tpcf` for the same set of radial bins and projection length. His results are compared against results deriving from Halotools, and the functions agree within the expected level of numerical noise. Both `Corrfunc` and `Halotools` were written independently, so this is a highly nontrivial test of code-correctness for both code bases. 
This PR resolves #546. 
Thanks to @surhudm who emphasized the importance of implementing this test prior to the v0.2 release.

Improve unit-testing of wp and tpcf

---

halotools/empirical_models/component_model_templates/scatter_models.py
halotools/empirical_models/component_model_templates/tests/test_scatter_models.py

This pull request allows scatter to be 0 for all scatter_abscissa or only some.  The root problem is that numpy.random.normal() throws an error if any value of scale<=0.0.  This fix only evaluates numpy.random.normal() for non-zero values of the scatter_scale variable.  
At some point where had something set up like:
result = np.where(scatter_scale > 0, np.random.normal(loc=0, scale=scatter_scale), 0)
,but numpy.where() evaluates both options before passing back the result, so this does not work (now, maybe it did previously, because I used to be able to use 0.0 scatter.)  
This bug request fixes https://github.com/astropy/halotools/issues/555

LogNormalScatterModel.scatter_realization error is scatter=0

---

README.md
docs/quickstart_and_tutorials/development/citing_halotools.rst

Now providing a link to http://arxiv.org/abs/1606.04106 in the README and also the Citation Info section. This will eventually be updated with the ADS entry and DOI when they become available.

Updated citation info

---

halotools/mock_observables/isolation_functions/engines/setup_package.py
halotools/mock_observables/pair_counters/cpairs/setup_package.py
halotools/mock_observables/pair_counters/marked_cpairs/setup_package.py
halotools/mock_observables/pairwise_velocities/engines/setup_package.py
halotools/mock_observables/radial_profiles/engines/setup_package.py

This PR removes a compiler optimization flag that causes Halotools v0.2 to fail to install on some architectures (RHEL 6.8 x86-64 and also whatever version of OS X used by @nickhand) resolving #560. The source of the failure is still a little mysterious to me, since I successfully installed v0.2 on two different OS X machines, and @duncandc and @eteq both reported successful installations in their OS X platforms. However, both @yymao and @nickhand both reported the same failure. Both have also reported that simply removing this flag resolves the bug. 
The `-march=native` optimization flag was suggested by @manodeep, who reported a ~4x speedup of his pair counters when using this flag. However, on my machine I only get a ~10% speedup when using this flag. Evidently cython is intelligent …

Removed -march=native compiler optimization

---

docs/quickstart_and_tutorials/tutorials/model_building/composing_models/hod_modeling/zheng07_using_cenocc_model_tutorial.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/zheng07_composite_model.rst
halotools/empirical_models/composite_models/hod_models/hearin15.py
halotools/empirical_models/composite_models/hod_models/tests/test_zheng07.py
halotools/empirical_models/composite_models/hod_models/zheng07.py
halotools/empirical_models/factories/hod_model_factory.py
halotools/empirical_models/factories/tests/test_hod_factory.py
halotools/empirical_models/factories/tests/test_hod_model_factory.py
halotools/empirical_models/occupation_models/leauthaud11_components.py
halotools/empirical_models/occupation_models/tests/test_zheng07_components.py
halotools/empirical_models/occupation_models/zheng07_components.py

Fixes issue #577. At the time of this request it is still under debate whether this change is appropriate. However, I believe this is the most natural way to resolve a bug in the way Zheng07Sats handles central modulation. 
Please note I have not run the test modules as my local setup does not support it. I can possible run later, but it would be helpful if someone else could check.

Resolve issue #577: modulate_with_cenocc changed to cenocc_model

---

CHANGES.rst
halotools/mock_observables/catalog_analysis_helpers.py
halotools/mock_observables/tests/test_catalog_analysis_helpers.py

New function in catalog_analysis_helpers can be used, for example, to calculate host-centric distances and host-relative velocities of satellites for equal-length arrays. 
CC @duncandc - I'm considering including the following new columns to all Halotools-provided catalogs: `halo_x_host_halo, halo_y_host_halo, halo_z_host_halo, halo_vx_host_halo, halo_vy_host_halo, halo_vz_host_halo, halo_distance_to_host`. These quantities would not actually stored on disk, but calculated from scratch using `crossmatch` the first time the `halo_table` is accessed. Does this seem like overkill? Or do you agree that these are common enough to consider basic subhalo properties that should be loaded into the catalogs by default?
Input welcome from anyone else who wants to weigh in.

Relative posvel

---

CHANGES.rst

Now explicitly pointing out the little-h patch to Behroozi10SmHm in the changelog so that users have a clear record of behavior change from version to version.
CC @duncandc.

Updated changelog 

---

halotools/mock_observables/catalog_analysis_helpers.py
halotools/mock_observables/tests/test_catalog_analysis_helpers.py

Modified return_xyz_formatted_array to accept a 3-element sequence for input period, for consistency with the rest of the package, resolving #594.

consistency for input period argument for return_xyz_formatted_array function

---

halotools/mock_observables/two_point_clustering/tests/test_s_mu_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf_estimators.py
halotools/mock_observables/two_point_clustering/tpcf_estimators.py
halotools/mock_observables/two_point_clustering/tpcf_jackknife.py

Modified all two-point functions to raise an exception before returning NaN values as a result of dividing by DR or RR with a zero in some bin.
Resolves #588. Suggestion due to @mclaughlin6464.

division by zero in two-point function calculations now raises exception

---

CHANGES.rst
docs/quickstart_and_tutorials/mock_observations/calculating_counts_in_cells.rst
halotools/mock_observables/__init__.py
halotools/mock_observables/counts_in_cells/__init__.py
halotools/mock_observables/counts_in_cells/counts_in_cylinders.py
halotools/mock_observables/counts_in_cells/engines/__init__.py
halotools/mock_observables/counts_in_cells/engines/counts_in_cylinders_engine.pyx
halotools/mock_observables/counts_in_cells/engines/setup_package.py
halotools/mock_observables/counts_in_cells/tests/pure_python_counts_in_cells.py
halotools/mock_observables/counts_in_cells/tests/test_counts_in_cylinders.py
halotools/mock_observables/pair_counters/cpairs/npairs_per_object_3d_engine.pyx

This PR introduces a new `mock_observables` function: counts_in_cylinders. The API is:
```
counts_in_cylinders(sample1, sample2, proj_search_radius, cylinder_length)
```
The function returns a length-Npts1 integer array storing the number of `sample2` points inside a cylinder around each point in `sample1`. 
**Optional feature.** The search radii and cylinder lengths are permitted to be vary from point-to-point in `sample1`, permitting the user, for example, to define a search radius according to a virial radius estimate of the `sample1` points (such as one based on stellar mass from abundance matching).

counts-in-cells sub-package

---

CHANGES.rst
halotools/mock_observables/isolation_functions/engines/cylindrical_isolation_engine.pyx
halotools/mock_observables/isolation_functions/engines/marked_cylindrical_isolation_engine.pyx

The variables `dz_sq` and `dxy_sq` had undeclared types inside the isolation engines. This PR updates the engine to include these variables, speeding up the performance of these functions by 50%-300% in numerical regimes typical of SDSS volumes. Thanks to @johannesulf for pointing this out.

Performance enhancement of isolation functions

---

halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/subhalo_mock_factory.py

This PR addresses issue #568 about the memory use of HodMockFactory.populate().

Added note about RAM usage of HodMockFactory.populate()

---

halotools/mock_observables/pair_counters/rectangular_mesh.py

This PR allows exposes the max_cells_per_dimension to the user to customize performance, which had previously been hidden behind nested function calls by accident. Thanks to @johannesulf for pointing this out. 
@johannesulf - would this modification have been sufficient to keep you from having to rewrite your own tree?

Exposed option to modify max_cells_per_dimension in double tree

---

halotools/mock_observables/pair_counters/cpairs/npairs_s_mu_engine.pyx

I noticed that s_mu_tpcf from from halotools.mock_observables is extremely slow and found that npairs_s_mu_engine.pyx had a very inefficient loop structure. I made small changes to the engine. s_mu_tpcf is now ~3 times faster when using 20 bins in s and mu. Previously, it took ~30 sec for a zheng07 mock (threshold -19) in bolplanck and now takes ~10 sec.
I have checked that the engine (and npairs_s_mu_engine.pyx) give identical results for this particular, non-trivial use case. I did not perform any other tests.

Performance improvement of npairs_s_mu_engine.pyx

---

halotools/mock_observables/pair_counters/mesh_helpers.py
halotools/mock_observables/pair_counters/test_pair_counters/test_mesh_helpers.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf.py

Improvement to the error message issued by the double-tree on attempts to look for neighbors over distances exceeding Lbox/3, as suggested by @villarrealas.

Improve search length error msg

---

halotools/empirical_models/component_model_templates/binary_galprop_models.py

Changed syntax of model galaxy property assignment so that table slice is explicitly modified in-place in accord with https://github.com/astropy/astropy/pull/5556.
This change has been made manually here but is identical to the change brought as part of #637 by
b28fe154370524d75ae625ada513272db49dad74. However, because the #637 PR has an entirely different purpose and has many other code changes that are entirely unrelated to this bugfix, #637 can instead be rebased against this commit for clarity.
Merging this PR will also resolve the test failures that occur in #638.
@bsipocz or @eteq - let me know if you know how to handle the git rewrite in a more elegant way (e.g., rolling back b28fe154370524d75ae625ada513272db49dad74), otherwise I'm fine with simply locally rebasing #637, locally …

Change Table column creation to be compatible with new astropy syntax

---

halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/hod_model_factory.py
halotools/empirical_models/model_defaults.py
halotools/empirical_models/phase_space_models/subhalo_based_models/__init__.py
halotools/empirical_models/phase_space_models/subhalo_based_models/subhalo_phase_space.py
halotools/empirical_models/phase_space_models/subhalo_based_models/subhalo_selection_kernel.py
halotools/empirical_models/phase_space_models/subhalo_based_models/tests/test_composite_model.py
halotools/empirical_models/phase_space_models/subhalo_based_models/tests/test_subhalo_phase_space.py
halotools/empirical_models/phase_space_models/subhalo_based_models/tests/test_subhalo_selection_kernel.py
halotools/mock_observables/catalog_analysis_helpers.py

This PR introduces the SubhaloPhaseSpace class to HOD profile modeling. Briefly, using this class subhalo positions and velocities can be chosen for HOD/CLF satellites, as opposed to analytical relations. 
This initial PR is currently just for testing and is unfinished as the `reverse_order` option still needs to be implemented, as discussed with @johannesulf.

Subhalo-based phase space model for satellites

---

docs/source_notes/empirical_models/factories/hod_mock_factory_source_notes.rst
halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/factories/tests/test_clf_support.py

This PR makes it simpler to implement the CLF using the existing factory design pattern. OccupationComponent subclasses can now assign additional galaxy properties (such as luminosity or stellar mass) after the `mc_occupation` method is called in the `mock_generation_calling_sequence`. 
CC @johannesulf.

Improve support for implementing the CLF using the HodMockFactory.

---

halotools/sim_manager/tests/test_user_supplied_ptcl_catalog.py
halotools/utils/array_utils.py
halotools/utils/table_utils.py

All related to passing a float for the number of points in Numpy functions such as np.linspace

Fixed bugs triggering Numpy Deprecation Warnings

---

halotools/empirical_models/phase_space_models/subhalo_based_models/tests/test_composite_model.py
halotools/empirical_models/phase_space_models/trivial_phase_space.py

This PR is intended to resolve #659, a forgotten fix needed to finish addressing #639.

Modified table-writing syntax in TrivialPhaseSpace class

---

CHANGES.rst
halotools/empirical_models/__init__.py
halotools/empirical_models/abunmatch/__init__.py
halotools/empirical_models/abunmatch/conditional_abunmatch.py
halotools/empirical_models/abunmatch/tests/test_conditional_abunmatch.py

This PR introduces the `abunmatch` subpackage of `empirical_models`. This subpackage provides general Numpy kernels for building conditional abundance matching-based models of the galaxy-halo connection, including variable levels of correlation strength. 
CC @duncandc @j-dr @mclaughlin6464 @johannesulf @alexieleauthaud @yymao

Added abunmatch subpackage

---

halotools/mock_observables/two_point_clustering/delta_sigma.py
halotools/mock_observables/two_point_clustering/tpcf.py

Now permitting max_sample_size to be set to infinity in delta_sigma calculation, as requested by @alexieleauthaud, resolving #670.

Relaxed max_sample_size requirement for delta_sigma calculation

---

docs/whats_new.rst

The `What's New?` section of the documentation had a couple of dead links to the `delta_sigma_from_precomputed_pairs function` that are now fixed

Fixed broken documentation link 

---

README.md

Typos were related to Markdown rendering of strings that include an underscore

Fixed a couple of typos in readme

---

halotools/utils/array_utils.py

Now casting num_downsample to be an int within namespace of randomly_downsample_data, resolving #708.

Bugfix for randomly_downsample_data function

---

docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/leauthaud11_composite_model.rst
docs/quickstart_and_tutorials/tutorials/model_building/preloaded_models/tinker13_composite_model.rst
docs/source_notes/empirical_models/phase_space_models/nfw_profile_source_notes.rst
halotools/empirical_models/factories/tests/test_prebuilt_hod_model_factory.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/nfw_phase_space.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_biased_nfw/test_biased_nfw_consistency_mockpop.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_biased_nfw/test_biased_nfw_phase_space_argument_handling.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_nfw_phase_space/test_nfw_phase_space_argument_handling.py
halotools/mock_observables/pair_counters/test_pair_counters/test_marked_npairs_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_marked_npairs_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_3d.py
halotools/mock_observables/two_point_clustering/tests/test_marked_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf.py

empirical_models and mock_observables were previously trying to import each other, causing an ImportError that was not caught by CI since Travis is currently failing due to unrelated reasons.

Resolve ImportError due to mutual imports

---

halotools/sim_manager/tests/test_halo_table_cache.py
halotools/sim_manager/tests/test_ptcl_table_cache.py

The `test_halo_table_cache.py` and `test_ptcl_table_cache.py` modules run unit-tests of the cache management system by creating temporary files in a (hidden) temporary sub-directory of $HOME that is then deleted after all the tests have been executed. Prior to this PR, some of the temporary files were accidentally created in the current working directory, rather than the temporary
directory, causing the testing files (e.g., fake halo catalogs and cache logs) to persist on disk after running the suite. The way the tests are written, the persistence of these files will lead failures if the test suite is called twice in succession from the same working directory for cases where the suite is executed via the method recommended in the docs:
```
>>> import halotools
>>> halotools.test()
``` …

Cleaned up the test suite for halo and particle table cache logs.

---

halotools/empirical_models/factories/hod_mock_factory.py

HodMockFactory now adds halo_num_gal_type to the halo_table, facilitating occupation models that are inter-dependent.

Fix HodMockFactory support for inter-dependent models

---

halotools/sim_manager/tests/test_cached_halo_catalog.py
halotools/sim_manager/tests/test_supported_sims.py

This PR relaxes a couple of unnecessary tests on CachedHaloCatalog, resolving #719 and #720.

Relax unit-testing requirements on halocat formatting

---

halotools/empirical_models/occupation_models/leauthaud11_components.py
halotools/empirical_models/occupation_models/tests/test_tinker13.py
halotools/empirical_models/occupation_models/tinker13_components.py
halotools/empirical_models/occupation_models/zheng07_components.py
halotools/empirical_models/occupation_models/zu_mandelbaum15_components.py

Now converting all prim_haloprop arguments with np.atleast_1d to protect against float vs. iterable confusion. This PR resolves #723.

Bugfix for occupation components

---

.travis.yml

Adding ``ASTROPY_USE_SYSTEM_PYTEST=1`` to the py3.6 builds should fix the failures, at least it worked for astroqeury (thanks @pllim for hinting that this issue should have been fixed upstream already).

Python3.6 needs pytest3 to pass

---

halotools/empirical_models/factories/hod_model_factory.py

This is to ensure consistency with the default settings for the mock-generation calling-sequence

Now sorting Hod model gal_types so that centrals appear first

---

docs/whats_new.rst
halotools/mock_observables/surface_density/delta_sigma.py

The docstring of delta_sigma now includes explicit discussion of how to project along alternative axes besides z, resolving #700. Thanks to @surhudm pointing out the apparent shortcoming and @johannesulf for pointing out the simple way to hack the code to achieve the desired result. 
The *What's New?* section of the documentation has also been updated to call explicit attention to the API change of `delta_sigma`, resolving #730.

Improved documentation on delta_sigma

---

halotools/empirical_models/abunmatch/noisy_percentile.py

After this PR, it will now be possible to import `noisy_percentile` function directly from `empirical_models as follows:
```
>>> from halotools.empirical_models import noisy_percentile
```
This did not work prior to this PR as a result of a forgotten `__all__`

Added forgotten `__all__` statement to noisy_percentile module

---

halotools/empirical_models/abunmatch/__init__.py

Modified __init__ so that randomly_resort function can be imported from top-level of empirical_models

Fix __init__ so that `randomly_resort` function can be imported

---

CHANGES.rst
docs/quickstart_and_tutorials/mock_observations/mock_obs_pos_formatting.rst
halotools/mock_observables/catalog_analysis_helpers.py
halotools/mock_observables/tests/test_catalog_analysis_helpers.py

Add option to the `return_xyz_formatted_array` function to apply z-space distortions assuming any cosmology and redshift.
Despite the feature-freeze, I am going to apply this to `v0.5` since this is borderline a bug in the code - at the very least the previous API was misleading and poorly documented.
Thanks to @johannesulf for the suggestion.

high-z redshift-distortion feature to `return_xyz_formatted_array` function

---

halotools/empirical_models/component_model_templates/scatter_models.py
halotools/empirical_models/smhm_models/tests/test_zu_mandelbaum15.py
halotools/empirical_models/smhm_models/zu_mandelbaum15.py

The `mc_stellar_mass` method of ZuMandelbaum15SmHm previously raised an exception due to some hard-coding of the model parameters governing the scatter. This PR provides a bug-fix for this behavior by over-riding the super-class methods. 
In a future PR, it may be better to just entirely do away with the template models for the SMHM, e.g., #746.

Fixed bug in ZuMandelbaum15SmHm

---

halotools/empirical_models/phase_space_models/analytic_models/monte_carlo_helpers.py

When generating velocity profiles by solving the Jeans equation, there are very occasional cases where a negative value will be passed to `radial_velocities = np.random.normal(scale=radial_dispersions)` during calls to the `mc_radial_velocity` function in the `MonteCarloGalProf` class. These negative values are always very small and are a numerical artifact of interpolation, but they cause the code to raise an exception. This PR clips these values to zero so that no exception is raised.

Bug-fix for Monte Carlo realizations of radial velocity profiles

---

halotools/empirical_models/factories/prebuilt_model_factory.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_biased_nfw/test_mockpop.py
halotools/empirical_models/smhm_models/zu_mandelbaum15.py

Testing the `tinker13` and `zu_mandelbaum15` models against externally provided code has ground to a halt for various reasons. Since the remainder of the code is ready for release and has been for months, I just added a caveat warning if users instantiate these models. 
The `zu_mandelbaum15` model now also no longer issues a warning if a different halo mass definition is used - this was redundant and already covered in the docstring.

Added science verification warning about tinker13 and zu_mandelbaum15

---

halotools/mock_observables/pair_counters/npairs_s_mu.py
halotools/mock_observables/two_point_clustering/s_mu_tpcf.py

Clarified difference in output shapes for s, mu-based pair-counting vs. s, mu-based correlation function, and gave explicit usage demo of how to import `npairs_s_mu` since this function cannot be imported from top-level `mock_observables`

Minor cleanup of docstrings to s_mu pair-counter and tpcf

---

halotools/empirical_models/assembias_models/heaviside_assembias.py
halotools/empirical_models/component_model_templates/binary_galprop_models.py
halotools/empirical_models/component_model_templates/prim_galprop_model.py
halotools/empirical_models/composite_models/hod_models/hearin15.py
halotools/empirical_models/composite_models/hod_models/tinker13.py
halotools/empirical_models/factories/subhalo_mock_factory.py
halotools/empirical_models/factories/subhalo_model_factory.py
halotools/empirical_models/smhm_models/behroozi10.py
halotools/empirical_models/smhm_models/moster13.py

@mclaughlin6464 - here's my first stab at the fix for #741. Let me know how this goes. I also did not add the `@wraps` decorator. That's a one-liner that we can try if necessary. 
This does not go all the way to eliminate all usages of `new_haloprop_func_dict`, so this does not resolve #752. That will require making adjustments to the HOD 1-halo term modeling, which will take a little more care.

Heaviside assembias pickle

---

appveyor.yml

This should fix #773 (actually is just a workaround).
You don't need to list numpy and astropy as those are taken care of with ``NUMPY_VERSION`` and ``ASTROPY_VERSION``. Also pytest is always installed by ci-helpers, as well as sphinx when it's a documentation build.

Removing superflous dependencies from CONDA_DEPENDENCIES

---

CHANGES.rst
halotools/mock_observables/pair_counters/cpairs/npairs_s_mu_engine.pyx
halotools/mock_observables/pair_counters/npairs_s_mu.py
halotools/mock_observables/pair_counters/pairs.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_s_mu.py
halotools/mock_observables/two_point_clustering/s_mu_tpcf.py

Completely un-tested, un-benchmarked. I am assuming there are existing tests for the npairs(s, mu) pair counters. 
Related to #763

Improving npairs(s, mu) performance and testing.

---

docs/notebooks/galcat_analysis/intermediate_examples/galaxy_catalog_intermediate_analysis_tutorial1.ipynb
docs/quickstart_and_tutorials/tutorials/catalog_analysis/galcat_analysis/intermediate_examples/isolation_criteria/galaxy_catalog_intermediate_analysis_tutorial1.rst

The tutorial incorrectly wrote `cond_func=5` instead of `cond_func=6` when describing how to implement stellar mass-dependent isolation criteria. This PR fixes the documentation.

Corrected error in isolation criteria tutorial

---

halotools/mock_observables/isolation_functions/cylindrical_isolation.py
halotools/mock_observables/isolation_functions/spherical_isolation.py
halotools/mock_observables/isolation_functions/tests/pure_python_isolation.py
halotools/mock_observables/isolation_functions/tests/test_brute_force_comparisons.py
halotools/mock_observables/isolation_functions/tests/test_pure_python_isolation.py

Fixed bug raised in #776. 
Error was very simple, and only relevant to users calculating isolation criteria without periodic boundary conditions. In the initial argument processing of both `spherical_isolation` and `cylindrical_isolation` functions:
`
x1, y2, z1 = sample1[:, 0], sample1[:, 2], sample1[:, 2]
`
has now been corrected to 
`
x1, y2, z1 = sample1[:, 0], sample1[:, 1], sample1[:, 2]
`
This bug was not revealed by the test suite prior to now because there was no brute force testing on a random set of points comparing to a pure python implementation of a naive isolation algorithm for non-PBC case. This PR also adds this brute force testing, for both periodic and non-periodic cases. These newly-introduced tests failed when the old code was run against them; now they pass. So these …

Isolation brute force

---

halotools/empirical_models/phase_space_models/analytic_models/tests/test_halo_boundary_functions.py

Added unit-test ensuring that `halotools.empirical_models.halo_mass_to_halo_radius` function agrees with `colossus.halo.mass_so.M_to_R` to better than 1% at z=0 and z=1 for `mdef=vir`.

Colossus testing

---

.travis.yml

Changed the `.travis` config file so that the `--coverage` option is run in python 3.6 instead of 2.7. For some reason this *decreases* coverage by 0.6%, but it resolves the weird test failures that showed up in #796. 
CC @bsipocz @astrofrog @eteq - I never did get to the bottom of why this happened, but I figured I'd point it out in case this is happening elsewhere. If the `--coverage` option runs on travis in a 2.7 environment, for some reason there is a mysterious failure with very little information available from googling:
`DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead`

Run --coverage test on Travis using py3.6 

---

CHANGES.rst
halotools/mock_observables/pairwise_velocities/los_pvd_vs_rp.py
halotools/mock_observables/pairwise_velocities/mean_los_velocity_vs_rp.py
halotools/mock_observables/pairwise_velocities/pairwise_velocities_helpers.py
halotools/mock_observables/pairwise_velocities/tests/test_pairwise_velocity_helpers.py
halotools/mock_observables/two_point_clustering/angular_tpcf.py
halotools/mock_observables/two_point_clustering/clustering_helpers.py
halotools/mock_observables/two_point_clustering/marked_tpcf.py
halotools/mock_observables/two_point_clustering/rp_pi_tpcf.py
halotools/mock_observables/two_point_clustering/s_mu_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_clustering_helpers.py
halotools/mock_observables/two_point_clustering/tests/test_rp_pi_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_s_mu_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf_one_two_halo.py
halotools/mock_observables/two_point_clustering/tests/test_wp.py
halotools/mock_observables/two_point_clustering/tpcf.py
halotools/mock_observables/two_point_clustering/tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/tpcf_one_two_halo_decomp.py
halotools/mock_observables/two_point_clustering/wp.py

As pointed out by @manodeep in #797, the `max_sample_size` argument creates a bookkeeping nuisance. I think this feature was originally included at a time when the code was just too slow to use this many points, but that is no longer the case. This PR removes this feature from all `mock_observables` functions. 
Will wait to hear from @duncandc before merging, in case I have forgotten an important reason this feature is here.

Delete `max_sample_size` feature from `mock_observables`

---

halotools/mock_observables/pair_counters/test_pair_counters/test_non_cubic_volumes.py

Added new unit-test explicitly checking xy-z pair-counter for non-PBC case where volume is non-cubic. Passes.

New unit-testing of non-cubical pair-counting

---

halotools/mock_observables/catalog_analysis_helpers.py
halotools/mock_observables/tests/test_catalog_analysis_helpers.py

New function in `apply_zspace_distortion` is more portable since it works with simple ndarrays and astropy cosmology, instead of halotools-formatted catalogs

Add stand-alone z-space distortion function

---

.travis.yml

Development version of astropy appears to have recently started enforcing 3.6 compatibility

Removing `ASTROPY_VERSION=development` from python 2.7.x testing matrix

---

CHANGES.rst
halotools/sim_manager/tabular_ascii_reader.py

This adds more flexibility to the reader so that it can deal with mixed header line conventions at the beginning of a file, which happens for some rockstar output jobs submitted on clusters

Added  optional keyword argument to TabularAsciiReader

---

CHANGES.rst
halotools/mock_observables/two_point_clustering/tpcf_jackknife.py

This PR addresses #815 and fixes a normalization error to the covariance matrices returned by the function.  This can easily result in a factor of ~10 difference in the resulting covariance.  
This issue has already been addressed in the wp_jackknife function.

bug fix for tpcf_jackknife

---

halotools/mock_observables/two_point_clustering/tpcf_jackknife.py

I changed one line from ```randoms = np.vstack((x,y,z)).T``` to ```randoms = np.vstack((xran,yran,zran)).T``` so that the example in the documentation is correct.

There was a typo in the documentation for the tpcf_jackknife function.

---

CHANGES.rst
halotools/mock_observables/two_point_clustering/__init__.py
halotools/mock_observables/two_point_clustering/rp_pi_tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/tests/test_rp_pi_tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/tests/test_wp_jackknife.py
halotools/mock_observables/two_point_clustering/wp_jackknife.py

This pull requests add a jackknife version of the rp_pi_tpcf function.  This feature was requested by @givoltage and discussed in #244.
This function is slightly more complicated than the other jackknife functions.  The observable had to be flattened in order to calculate the covariance matrix.  I would feel more comfortable if someone tries out this function before we fully merge it into master.

adding rp_pi_tpcf_jackknife function to mock_observables 

---

.travis.yml

Modified the .travis configuration to drop testing python 3.5 with Numpy v1.10 due to persistent failures that I couldn't track down. The first failure happened in #838, but was resolved after a simple rebuild. #839 didn't have any failures, but then all subsequent PRs failed in this environment configuration, and these failures became persistent. 
In #842, which simply updates the changelog, the entire test suite executes without failure, but then all the doctests located in ``../docs/*.rst`` fail with a mysterious ImportError. 
I attempted to resolve these failures in #845 by rolling back all changes introduced in #838, and in #844 by modifying a couple of specific tests, and in #846 by changing the configuration to Numpy v1.10 with python 3.6 (which is not allowed). I'm basically out …

Removed python=3.5, numpy=1.10 testing configuration

---

halotools/empirical_models/phase_space_models/analytic_models/monte_carlo_helpers.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_biased_nfw/test_conc_gal_bias_behavior.py

Now doing the following before generating radial profiles:
radial_dispersions = np.where(radial_dispersions <= 0, _epsilon, radial_dispersions),
where _epsilon = 0.001
This protects against calling np.random.normal with `scale` values equal to zero, raising exceptions in older versions of numpy

Improved numerical stability of monte_carlo_helpers mc_radial_velocity

---

halotools/empirical_models/composite_models/hod_models/zheng07.py
halotools/empirical_models/composite_models/tests/test_preloaded_models.py
halotools/empirical_models/factories/hod_model_factory.py

This PR fixes two problems leading to bug report #827:
1. The **zheng07_model_dictionary** function accepts arbitrary kwargs but does not pass them on down to **Zheng07Cens**. No other pre-loaded composite model dictionaries appear to have missed this argument, so this problem appears to have been limited to the **zheng07_model_dictionary** composite model. 
2. The **HodModelFactory** builds a private list called __haloprop_list_ that is the union of each component model's requested properties. Phase space models all must define a quantity _halo_boundary_key_ that will be used to identify the corresponding column of a halo catalog. The _halo_boundary_key_ was not appended to __haloprop_list_. This results in KeyError exceptions when the **HodMockFactory** attempts to populate a halo …

Prim haloprop key propagation

---

halotools/mock_observables/pair_counters/test_pair_counters/test_weighted_npairs_s_mu.py
halotools/mock_observables/pair_counters/weighted_npairs_s_mu.py

This addresses issue #837
When num_threads > 1 the list returned by multiprocessing.map was not indexed properly.  This has now been resolved by turning it into an array before pulling out the weighted and unweighted counts.

weighted npairs s mu bugfix

---

CHANGES.rst
halotools/mock_observables/pairwise_velocities/engines/velocity_marked_npairs_3d_engine.pyx
halotools/mock_observables/pairwise_velocities/engines/velocity_marked_npairs_xy_z_engine.pyx
halotools/mock_observables/pairwise_velocities/engines/velocity_marking_functions.pyx
halotools/mock_observables/pairwise_velocities/los_pvd_vs_rp.py
halotools/mock_observables/pairwise_velocities/mean_los_velocity_vs_rp.py
halotools/mock_observables/pairwise_velocities/tests/test_velocity_marked_npairs_3d.py
halotools/mock_observables/pairwise_velocities/velocity_marked_npairs_3d.py
halotools/mock_observables/pairwise_velocities/velocity_marked_npairs_xy_z.py

This pull request addresses issue #836.  
There is no weight_func_id=0 for these velocity weighted functions.  In addition, each function was being called incorrectly within the doc string example section.  
I have corrected these bugs and modified the ``weight_func_id`` numbers of each weighting function to be more reasonable, e.g. 1,2,3,4.  This change required updating ``weight_func_id`` in a couple other locations with the `pairwise_velocities module`.  These changes have been noted CHANGES.rst

bug fix in velocity_marked_npairs functions

---

halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_jackknife_xy_z.py
halotools/mock_observables/two_point_clustering/rp_pi_tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/tests/test_rp_pi_tpcf_jackknife.py

This pull requests improves the testing of `rp_pi_tpcf_jackknife` to include a consistency test between itself and `wp_jackknife` including the covariance matrices.  This should address issue #830.

improved testing of rp_pi_tpcf_jackknife()

---

halotools/utils/inverse_transformation_sampling.py

Warnings related to np.dtype changing size are now filtered out by the inverse_transformation_sampling module

Filtering out scipy warnings

---

halotools/utils/matrix_operations_3d.py

The `rotate_vector_collection` function in `matrix_operations_3d` omitted a return statement for one of its logical branches, so `void` was being returned. This PR resolves bug #874.

Fixed bug in rotate_vector_collection

---

CHANGES.rst
docs/whats_new_history/whats_new_0.7.rst
halotools/utils/__init__.py
halotools/utils/conditional_percentile.py
halotools/utils/engines/__init__.py
halotools/utils/engines/conditional_rank_kernel.pyx
halotools/utils/engines/setup_package.py
halotools/utils/tests/test_conditional_percentile.py

New function `sliding_conditional_percentile` calculates Prob(< y | x) by sliding a window along the distribution and computing the rank-order of each element in the window. The target application is conditional abundance matching and/or decorated HODs where the rank-order percentile of some secondary halo property needs to be calculated on-the-fly at each step in an MCMC (enabling the secondary variable itself to be a model parameter). The performance trick is to only sort the elements in the window once at the beginning, and then pop elements in and out while maintaining the sorted order. So this function enables the CAM-analog to what @yymao has done for 1-dimensional abundance for smooth variations between {Mvir, Vmax}. 
Tagging @mclaughlin6464, as he may find use for this function in …

Sliding percentile feature

---

halotools/utils/conditional_percentile.py
halotools/utils/tests/test_conditional_percentile.py

For cases where galaxies/halos can be pre-sorted according to, e.g., stellar or halo mass, the __assume_x_is_sorted__ argument can now be used to improve performance of the calculation of Prob(< y | x).

Added assume_x_is_sorted keyword argument to sliding_conditional_percentile

---

halotools/utils/conditional_percentile.py
halotools/utils/tests/test_conditional_percentile.py

Using this keyword minimizes the impact of discreteness effects caused by the finite window size over which Prob(<y | x) is estimated by the `sliding_conditional_percentile` function. This bug was discovered when using the `sliding_conditional_percentile` function to generate mock catalogs for LSST-DESC; the bug becomes more apparent when modeling very large galaxy samples. This PR fixes the bug.

Added add_subgrid_noise feature to sliding_conditional_percentile

---

docs/function_usage/utility_functions.rst
halotools/utils/matrix_operations_3d.py

New function in `matrix_operations_3d` takes an input list of 3d vectors, `x` and `y`, each of shape (npts, 3), as well as an input ndarray of shape (npts, ) with values in the closed interval [0, 1]. The returned values are 3d vectors `v` that lie in the plane spanned by `x` and `y`, and point in the direction in between  `x` and `y`, where "between-ness" is controlled by the input `p`. 
Function is used in the LSST-DESC mocks for preserving satellite orientations, and also may be useful for modeling intrinsic alignments. 
CC @duncandc

Implemented vectors_between_two_lists_of_vectors function 

---

halotools/utils/matrix_operations_3d.py

In the previous implementation, the returned vector was the same length as whatever the length of the input `x` was. This PR changes this arbitrary and bug-prone convention.

vectors_between_list_of_vectors now returns unit-normalized results

---

CHANGES.rst
docs/function_usage/utility_functions.rst
halotools/utils/distribution_matching.py
halotools/utils/tests/test_distribution_matching.py

The `resample_x_to_match_y` function is used in the cosmoDC2 pipeline to make mocks for LSST-DESC.

Added new `resample_x_to_match_y` function to `halotools.utils`

---

CHANGES.rst
docs/function_usage/abundance_matching.rst
halotools/empirical_models/abunmatch/__init__.py
halotools/empirical_models/abunmatch/conditional_abunmatch_bin_based.py
halotools/empirical_models/abunmatch/tests/test_conditional_abunmatch.py
halotools/utils/inverse_transformation_sampling.py

New function is named conditional_abunmatch_bin_based. The purpose of this PR is to clear the namespace for a soon-to-be-added new implementation of conditional abundance matching that is entirely bin-free. This will unfortunately break backwards compatibility.
CC @h-aung @manodeep @duncandc

Renamed conditional_abunmatch function

---

halotools/empirical_models/phase_space_models/subhalo_based_models/subhalo_phase_space.py

Thanks to @johannesulf for pointing this out in #900 . 
It might be a good idea if the behavior of a few other Halotools functions such as `enforce_periodicity_of_box` were modified to automatically wrap `x == Lbox` points to `x == 0.` Any thoughts on this @johannesulf?

Added support for `x==Lbox` points for SubhaloPhaseSpace model

---

CHANGES.rst
docs/function_usage/utility_functions.rst
halotools/utils/__init__.py
halotools/utils/crossmatch.py
halotools/utils/satellite_rotations.py
halotools/utils/tests/test_compute_richness.py
halotools/utils/tests/test_satellite_rotations.py

This PR introduces a new `satellite_rotations` module to the `utils` sub-package. This module contains the following three user-facing functions, each of which accounts for periodic boundary conditions:
1. __rotate_satellite_vectors__ - Given a collection of satellites that each possess some vector (such the orientation of each satellite's shape, or the host-centric radial vector of each satellite), rotate each satellite's vector by an input angle about the axis associated with the satellite's host halo. The rotation angle is permitted to vary from satellite to satellite within the same host, but all satellites in the same halo will be rotated about the same rotation axis. 
2. __calculate_satellite_radial_vector__ - Given the 3d position of a collection of satellites, and given each …

Satellite rotations pr

---

.gitignore
halotools/empirical_models/abunmatch/bin_free_cam.py
halotools/empirical_models/abunmatch/engines/__init__.py
halotools/empirical_models/abunmatch/engines/bin_free_cam_kernel.pyx
halotools/empirical_models/abunmatch/tests/test_bin_free_cam.py

As discussed in person + slack the primary goal of this is to:
* Add an option to return the index of y2 that was matched (rather than the value in y2) to the CAM code
I made one other minor change - previously, subgrid noise was not being added to the left and right edges. Now it should be.
I've put a number of comments on the PR where I have done something I am not sure about. Let me know what you think!

Add option to return indexes in conditional abundance matching

---

halotools/empirical_models/assembias_models/__init__.py
halotools/empirical_models/assembias_models/heaviside_assembias.py
halotools/empirical_models/occupation_models/occupation_model_template.py
halotools/empirical_models/occupation_models/zheng07_components.py

This PR is to ensure that:
1. When populating a Decorated HOD mock *with a specific seed*, the total number of galaxies will remain the same. 
2. When populating HOD mocks using *same specific seed* but different HOD parameters, for each mock, the relative deviation between the total number of galaxies and the mean occupation will be preserved. 
Here's an example of how the number of galaxies changes with `alpha` and `A_cen` in the `AssembiasZheng07` model *with a fixed seed*: 
For analyses that require a smooth response to the change in parameters, the behavior in this PR when a seed is specified is very desirable. 
Thanks to @KuanWang-Astro for discovering this. (cc @andrew-zentner @mclaughlin6464)
(This PR was originally accidentally submitted to …

HOD mock preserving total number of galaxies (and relative deviation) when a seed is specified

---

halotools/empirical_models/abunmatch/bin_free_cam.py
halotools/empirical_models/abunmatch/tests/test_bin_free_cam.py

Changed default behavior of conditional_abunmatch so that add_subgrid_noise is automatically set to False when return_indexes is True

Change default behavior of return_indexes feature of conditional_abunmatch

---

halotools/empirical_models/phase_space_models/analytic_models/monte_carlo_helpers.py

This PR is intended to fix the following warnings:
```
build/testenv/lib/python3.6/site-packages/nbodykit/source/catalog/tests/test_hod.py::test_hod_cm[1]
/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/halotools/empirical_models/phase_space_models/analytic_models/monte_carlo_helpers.py:205: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
self.rad_prof_func_table_indices[digitized_param_list]
/home/yfeng1/anaconda3/install/lib/python3.6/site-packages/halotools/empirical_models/phase_space_models/analytic_models/monte_carlo_helpers.py:522: FutureWarning: …
```

fix for numpy 1.15 indexing changes

---

halotools/empirical_models/composite_models/tests/test_preloaded_models.py
halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/model_factory_template.py

This PR removes the reference cyels between MockFactory and ModelFactory.
I used objgraph to dump the back references in `halotools/empirical_models/composite_models/tests/test_preloaded_models.py::test_hearin15`
Before the PR:
After the PR:
Unfortunately this does not cure #917. Memory usage still increase after these cycles are cured. There must be other cycles that I haven't found yet.

Remove reference cycles between MockFactory and ModelFactory.

---

halotools/empirical_models/smhm_models/behroozi10.py

When the model parameters of the Behroozi+10 model are set to especially large/small values (as commonly the case in an MCMC), the code attempts to numerically invert the halo-to-stellar-mass relation using lookup tables with infinite values, leading to mysterious errors for users. This PR improves the error handling by raising a warning whenever the lookup tables have one or more infinite values. Thanks to @MehnaazAsad for tracking this down and suggesting this improvement.

Improved error message of Behroozi+10 model 

---

halotools/mock_observables/counts_in_cells/counts_in_cylinders.py
halotools/mock_observables/counts_in_cells/engines/counts_in_cylinders_engine.pyx
halotools/mock_observables/counts_in_cells/tests/test_counts_in_cylinders.py

In the case where there is only one pair, return indexes would return
```array((1086, 143), dtype=[('i1', '<u4'), ('i2', '<u4')])``` which is not an array and so can't be treated in the same way as the normal output which looks like
```array([(1086, 143), ( ... ),  ], dtype=[('i1', '<u4'), ('i2', '<u4')])```
What I'm pretty sure we want is to be consistent. This changes makes it look lie
```array([(1086, 143)], dtype=[('i1', '<u4'), ('i2', '<u4')])```

Fix inconsistent return idx

---

halotools/conftest.py
halotools/empirical_models/component_model_templates/binary_galprop_models.py
halotools/empirical_models/component_model_templates/prim_galprop_model.py
halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/model_factory_template.py
halotools/empirical_models/occupation_models/occupation_model_template.py
halotools/empirical_models/phase_space_models/analytic_models/profile_model_template.py
halotools/mock_observables/void_statistics/underdensity_prob_func.py
halotools/mock_observables/void_statistics/void_prob_func.py
halotools/sim_manager/download_manager.py
halotools/sim_manager/supported_sims.py
halotools/sim_manager/tabular_ascii_reader.py
halotools/utils/io_utils.py
halotools/utils/tests/test_value_added_halo_table_functions.py

as we're about to remove it from astropy.
The PR also fixes the pytest plugin imports.

Switch to standalone six

---

halotools/mock_observables/surface_density/__init__.py
halotools/mock_observables/surface_density/delta_sigma.py
halotools/mock_observables/surface_density/engines/__init__.py
halotools/mock_observables/surface_density/engines/mean_delta_sigma_engine.pyx
halotools/mock_observables/surface_density/engines/mean_ds_one_two_halo_decomp_halo_id_engine.pyx
halotools/mock_observables/surface_density/engines/mean_ds_one_two_halo_decomp_rhalo_engine.pyx
halotools/mock_observables/surface_density/engines/setup_package.py
halotools/mock_observables/surface_density/mean_delta_sigma.py
halotools/mock_observables/surface_density/mean_delta_sigma_one_two_halo_decomp.py
halotools/mock_observables/surface_density/tests/test_mean_delta_sigma.py

Merging in the `mean_delta_sigma` function written by @johannesulf. 
Currently keeping the name `mean_delta_sigma`, although I think this function should outright replace the existing `delta_sigma` function. The question is whether people who use Halotools for lensing calculations would be bothered, so soliciting input from @Christopher-Bradshaw, @dr-guangtou, @alexieleauthaud, and whoever else uses this function.

Mean delta sigma 

---

halotools/empirical_models/phase_space_models/analytic_models/monte_carlo_helpers.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_biased_nfw/test_biased_nfw_consistency_mockpop.py

This PR should resolve #963 , and also resolve many deprecation warnings the code currently raises when populating mocks.

Changed profile parameter indexing to use tuple rather than list

---

halotools/mock_observables/two_point_clustering/wp_jackknife.py

The wp_jackknife doctest was timing out in some CI builds. This PR reduces the number of points in the doctest calculation.

Shortened length of wp_jackknife doctest

---

halotools/empirical_models/factories/mock_factory_template.py
halotools/empirical_models/factories/model_factory_template.py

Apparently indented function definitions are no longer supported by sphinx?

Resolved warnings raised by doctests

---

halotools/mock_observables/occupation_stats.py

Bug was caused by caused by change to scipy default behavior for None arguments in scipy.stats.binned_statistic function.

Resolved bug in hod_from_mock 

---

halotools/sim_manager/cached_halo_catalog.py
halotools/sim_manager/tests/test_cached_halo_catalog.py

The CachedHaloCatalog was failing to recognize that an input simulation matched a previously cached simulation. The cause of the problem was string-to-bytes comparisons in python 3. This PR resolves the bug by using the `compare_strings_py23_safe` function.

Fixed bug in CachedHaloCatalog treatment of simname

---

halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/kernels/mc_generate_nfw_radial_positions.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_nfw_profile/test_nfw_profile.py

Relaxed requirement that monte carlo realizations of NFW profiles must respect a SO mass definition

---

docs/install.rst
docs/installing_halotools_with_virtualenv.rst
halotools/empirical_models/composite_models/hod_models/tests/test_zheng07.py
halotools/empirical_models/factories/hod_mock_factory.py
halotools/empirical_models/phase_space_models/analytic_models/centrals/trivial_phase_space.py
halotools/empirical_models/phase_space_models/analytic_models/profile_model_template.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/biased_nfw_phase_space.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/nfw_phase_space.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/nfw_profile.py

This PR should resolve #993. Previously, the user supplied only the halo mass column name, and halotools enforced a specific string pattern for the column name in the halo catalog associated with the halo mass definition. This PR allows users to pass in a halo_boundary_key kwarg that overrides this choice.

New keyword argument supports user-defined halo boundary

---

halotools/empirical_models/occupation_models/occupation_model_template.py
halotools/empirical_models/occupation_models/tests/test_occupation_component.py
halotools/empirical_models/occupation_models/tests/test_zheng07_satellites.py

PR adds support for the Monte Carlo realizations of satellite occupation statistics to follow a weighted nearest-integer distribution.
CC @johannesulf

Add support for non-Poissonian satellite occupation statistics

---

halotools/empirical_models/occupation_models/occupation_model_template.py

Currently, the function `_weighted_nearest_integer` function returns floats when it should return integers. This leads to crashes if one wants to populate a halo catalog with an HOD model that has non-Poisson numbers for satellites. This PR fixes that.

fixed bug for weighted nearest integer distributions

---

halotools/_astropy_init.py

This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497

MNT: Remove unused astropy config code

---

.github/workflows/wheels.yml

This short PR adds a GitHub action that will automatically trigger the build of python wheels for all versions of python above 3.6 for both Mac (intel) and linux architectures. It uses the excellent https://cibuildwheel.readthedocs.io/ tool that makes all of this very simple.
For maintainers, here are the steps to follow upon a new code release:
- Use the github release tool to tag a new version
- Go get a coffee for like 30 mins
- Go the Actions tab and find the latest `Build wheels` run, download the attached `artifact`
- Unzip the artifact
- Upload to pypi with: `twine upload  *.whl`
This is in addition to uploading the normal source distribution. Eventually the entire process can be automatized if you create a pypi key so that the action can directly push to pypi.
After that, a user …

Adding GitHub Action to produce Python Wheels for Linux and Mac

---

halotools/mock_observables/two_point_clustering/angular_tpcf.py
halotools/mock_observables/two_point_clustering/rp_pi_tpcf.py
halotools/mock_observables/two_point_clustering/rp_pi_tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/s_mu_tpcf.py
halotools/mock_observables/two_point_clustering/tests/test_tpcf_estimators.py
halotools/mock_observables/two_point_clustering/tpcf.py
halotools/mock_observables/two_point_clustering/tpcf_estimators.py
halotools/mock_observables/two_point_clustering/tpcf_jackknife.py
halotools/mock_observables/two_point_clustering/tpcf_one_two_halo_decomp.py
halotools/mock_observables/two_point_clustering/wp_jackknife.py

This PR brings in a fix for the calculation of two-point cross-correlations based on the Hamilton and Landy-Szalay estimators. Thanks to @ts485 for calling attention to this error.

Bug fix for cross-correlations with non-natural estimators

---

.github/workflows/wheels.yml

According to [this issue](https://github.com/actions/virtual-environments/issues/5583), wheels based on macos-10.15 are now deprecated. This updates the Action brought in by #1017 so that macos-11 is now used instead.
Tagging @EiffL in case he has any other suggestions for wheel updates. If not, this is the last planned commit prior to releasing v0.8.

Update build wheel to macos-11

---

.github/workflows/wheels.yml
halotools/empirical_models/assembias_models/heaviside_assembias.py
pyproject.toml
setup.py

In PR #1047 halotools removed dependency on the astropy-helpers and began using extensions-helpers to handle the automation of the cython extensions. In the current master branch, [the cibuildwheel github action](https://github.com/astropy/halotools/blob/master/.github/workflows/wheels.yml) in current master branch [fails to successfully build a wheel](https://github.com/astropy/halotools/actions/runs/3122524070/jobs/5064519017) to upload to pypi. This PR attempts to resolve this failure.

Resolve cibuildwheel failures

---

README.rst
docs/install.rst
halotools/sim_manager/tests/test_download_manager.py

Updated docs notify users that conda-forge is the preferred installation method over pip

Update installation instructions

---

halotools/empirical_models/occupation_models/leauthaud11_components.py
halotools/empirical_models/occupation_models/tests/test_leauthaud11_hod.py

This PR resolves #1061 as follows:
- The new Leauthaud11 has parameter values that assume h=0.72, so that the numerical values in the parameter dictionary can be directly compared to Leauthaud+11.
- The input stellar mass threshold is quoted in h=1, so that the user needs to rescale the stellar mass of their sample before directly comparing parameter values.
- All user-facing functions such as `mean_stellar_mass` and `mean_log_halo_mass` accept and return values of mass in h=1 units, for consistency with the rest of the package.
- There is no longer any dependence upon Behroozi10SmHm. Instead, there is a new Leauthaud11SmHm class defined within the same module. This simplifies the complication that Behroozi+10 assumed h=0.7, whereas Leauthaud+11 assumed h=0.72.
Throughout the docstrings, …

Implement fix for inconsistent treatment of littleh in Leauthaud+11 model

---

halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/nfw_phase_space.py

Docstring edits explicitly point out that negative (positive) relative velocities correspond to approaching (receding) points. Resolves #1054

Improve docstring clarifying sign convention of radial velocities

---

.github/workflows/wheels.yml

Temporarily build wheels with each PR to check build success before next release

Check build wheels for upcoming release of 0.8.3

---

.github/workflows/wheels.yml

Hi, version 4 of upload-artifact and download-artifact were recently released.
Staying on old version is not viable long term because GitHub will sooner or later drop support for the old versions of node that these depend on.
Since migration to v4 is not as straightfoward as bumping the version number, I'm helping all astropy-related packages byt manually performing the necessary changes.

MNT: upgrade upload/download-artifact GitHub actions

---

halotools/mock_observables/two_point_clustering/tpcf_jackknife.py

In line 416--418 of halotools/mock_observables/two_point_clustering/tpcf_jackknife.py, np.min(x3), np.min(y3), and np.min(y3) are supposed to be np.max(x3), np.max(y3), np.max(y3), right?

Typo in tpcf_jackknife.py?

---

.github/workflows/ci_tests.yml
halotools/empirical_models/occupation_models/occupation_model_template.py
halotools/empirical_models/occupation_models/tests/test_cacciato09_clf.py
halotools/empirical_models/occupation_models/tests/test_occupation_component.py

This PR adds a check that the mean occupation for all halos is non-negative. If it's negative but reasonably close to 0 such that this may be caused by rounding errors, the mean occupation will be 0 exactly. If it's clearly negative, `halotools` will raise an error to alert the user that the model is unphysical. This should fix #1081.
@aphearin This PR also adds the above check for centrals and satellites. Let me know if this PR could produce any unwanted exceptions.

Fix crashes due to rounding errors in mean_occupation functions

---

.github/workflows/cron_tests.yml
pyproject.toml
requirements.txt
setup.cfg

Add new cron workflow that runs CI tests as a cron job every month

Add new cron workflow

---

docs/conf.py

As noticed by @pllim a recent PR (probably #1093) broke the readthedocs formatting. This PR attempts to fix.

Fix readthedocs formatting issues

---

.github/workflows/ci_tests.yaml
.github/workflows/cron_tests.yaml
.github/workflows/wheels.yaml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed

---

halotools/empirical_models/composite_models/hod_models/tests/test_zu_mandelbaum16.py
halotools/empirical_models/factories/tests/test_hod_mock_factory.py
halotools/empirical_models/factories/tests/test_prebuilt_hod_model_factory.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_biased_nfw/test_biased_nfw_consistency_mockpop.py
halotools/empirical_models/phase_space_models/analytic_models/satellites/nfw/tests/test_conc_mass_inheritance/test_direct_from_halo_catalog.py
halotools/mock_observables/pair_counters/test_pair_counters/test_marked_npairs_3d.py
halotools/mock_observables/pair_counters/test_pair_counters/test_marked_npairs_xy_z.py
halotools/mock_observables/pair_counters/test_pair_counters/test_npairs_3d.py
halotools/mock_observables/two_point_clustering/tests/locate_external_unit_testing_data.py
halotools/sim_manager/__init__.py
halotools/sim_manager/tests/helper_functions.py
halotools/sim_manager/tests/test_cached_halo_catalog.py
halotools/sim_manager/tests/test_download_manager.py
halotools/sim_manager/tests/test_halo_table_cache.py
halotools/sim_manager/tests/test_halo_table_cache_log_entry.py
halotools/sim_manager/tests/test_load_default_halocat.py
halotools/sim_manager/tests/test_ptcl_table_cache.py
halotools/sim_manager/tests/test_ptcl_table_cache_log_entry.py
halotools/sim_manager/tests/test_rockstar_hlist_reader.py
halotools/sim_manager/tests/test_supported_sims.py
halotools/sim_manager/tests/test_tabular_ascii_reader.py
halotools/sim_manager/tests/test_user_supplied_halo_catalog.py
halotools/sim_manager/tests/test_user_supplied_ptcl_catalog.py
halotools/tests/docs_code_block_tests/test_preloaded_mockpop.py
requirements.txt

This should hopefully fix #1106

MAINT: remove usage of removed astropy functionality _find_home()

---

.github/workflows/wheels.yaml

macos-12 has been removed, this should fix CI for that job

CI: update macos version

---

.github/workflows/ci_tests.yaml
.github/workflows/cron_tests.yaml
.readthedocs.yaml
docs/installing_halotools_with_virtualenv.rst
halotools/empirical_models/occupation_models/tinker13_components.py
halotools/mock_observables/pair_counters/cpairs/pairwise_distance_3d_engine.pyx
halotools/mock_observables/pair_counters/cpairs/pairwise_distance_xy_z_engine.pyx
halotools/mock_observables/pair_counters/cpairs/pairwise_distances.pyx
halotools/mock_observables/pair_counters/marked_cpairs/conditional_pairwise_distances.pyx
halotools/sim_manager/cached_halo_catalog.py
halotools/sim_manager/rockstar_hlist_reader.py
halotools/sim_manager/user_supplied_halo_catalog.py
halotools/sim_manager/user_supplied_ptcl_catalog.py
pyproject.toml
requirements.txt

This pull request brings halotools up to date with numpy 2 to bring #1084 to a close. Build system now requires numpy>=2, which compiles code compatible with both numpy 1 and 2.
Edit: Might still need to replace `oldest-supported-numpy` with `numpy>=2` [here](https://github.com/astropy/halotools/blob/master/.github/workflows/wheels.yaml#L30)?

Add support for numpy 2

---

.github/workflows/wheels.yaml
.readthedocs.yaml

As recommended by actions/runner-images#11101 , this PR replaces the deprecated ubuntu-20.04 runner with a newer version. This also replaces RTD workflow, if applicable, to future-proof the build in case it follows suit.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/63)

MNT: Replace ubuntu-20.04 with ubuntu-22.04

---

halotools/mock_observables/counts_in_cells/engines/counts_in_cylinders_engine.pyx

This PR will provide a solution to the ValueError in galtab [issue 6](https://github.com/AlanPearl/galtab/issues/6) and does not degrade performance. I'll leave the example test script here, since it is too expensive to include as a unit test:
```
import numpy as np
import halotools.mock_observables as htmo
sample = np.zeros((40_000, 3))
htmo.counts_in_cylinders(sample, sample, 1, 1, return_indexes=True, period=100)
```

Count cic indexes with int64 to prevent overflow

---

.github/workflows/wheels.yaml

https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/#macos-13-is-closing-down

BLD: Remove macos-13
